# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editeqcheckdetail.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(589, 215)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.dateEdit_checkdate = QtWidgets.QDateEdit(Dialog)
        self.dateEdit_checkdate.setCalendarPopup(True)
        self.dateEdit_checkdate.setObjectName("dateEdit_checkdate")
        self.gridLayout.addWidget(self.dateEdit_checkdate, 0, 1, 1, 1)
        self.comboBox_company = QtWidgets.QComboBox(Dialog)
        self.comboBox_company.setEditable(True)
        self.comboBox_company.setObjectName("comboBox_company")
        self.gridLayout.addWidget(self.comboBox_company, 1, 1, 1, 1)
        self.lineEdit_result = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_result.setObjectName("lineEdit_result")
        self.gridLayout.addWidget(self.lineEdit_result, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_accept = QtWidgets.QPushButton(Dialog)
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.horizontalLayout.addWidget(self.pushButton_accept)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.pushButton_apply = QtWidgets.QPushButton(Dialog)
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.horizontalLayout.addWidget(self.pushButton_apply)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "校验日期："))
        self.label_3.setText(_translate("Dialog", "校验结果："))
        self.label_2.setText(_translate("Dialog", "校验单位："))
        self.pushButton_accept.setText(_translate("Dialog", "确认"))
        self.pushButton_cancel.setText(_translate("Dialog", "取消"))
        self.pushButton_apply.setText(_translate("Dialog", "提交完成"))
