# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eqrunnote.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 347)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.comboBox_startstatus = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_startstatus.setObjectName("comboBox_startstatus")
        self.comboBox_startstatus.addItem("")
        self.comboBox_startstatus.addItem("")
        self.comboBox_startstatus.addItem("")
        self.comboBox_startstatus.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_startstatus)
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.comboBox_stopstatus = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_stopstatus.setObjectName("comboBox_stopstatus")
        self.comboBox_stopstatus.addItem("")
        self.comboBox_stopstatus.addItem("")
        self.comboBox_stopstatus.addItem("")
        self.comboBox_stopstatus.addItem("")
        self.horizontalLayout_4.addWidget(self.comboBox_stopstatus)
        self.gridLayout.addWidget(self.groupBox_5, 5, 3, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_3.addWidget(self.checkBox_6, 0, 1, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_3.addWidget(self.checkBox_4, 0, 0, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_3.addWidget(self.checkBox_5, 1, 0, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_3.addWidget(self.checkBox_7, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 3, 3, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_1 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_1.setObjectName("checkBox_1")
        self.horizontalLayout.addWidget(self.checkBox_1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout.addWidget(self.checkBox_3)
        self.gridLayout.addWidget(self.groupBox_2, 2, 3, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout_3.addWidget(self.checkBox_8)
        self.checkBox_9 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_9.setObjectName("checkBox_9")
        self.horizontalLayout_3.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_10.setObjectName("checkBox_10")
        self.horizontalLayout_3.addWidget(self.checkBox_10)
        self.gridLayout.addWidget(self.groupBox_4, 4, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_equipment = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_equipment.sizePolicy().hasHeightForWidth())
        self.label_equipment.setSizePolicy(sizePolicy)
        self.label_equipment.setText("")
        self.label_equipment.setObjectName("label_equipment")
        self.horizontalLayout_2.addWidget(self.label_equipment)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.pushButton_filler = SignButton(Dialog)
        self.pushButton_filler.setText("")
        self.pushButton_filler.setObjectName("pushButton_filler")
        self.gridLayout.addWidget(self.pushButton_filler, 6, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 0, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cancel.sizePolicy().hasHeightForWidth())
        self.pushButton_cancel.setSizePolicy(sizePolicy)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 7, 3, 1, 1)
        self.pushButton_accept = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_accept.sizePolicy().hasHeightForWidth())
        self.pushButton_accept.setSizePolicy(sizePolicy)
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.gridLayout.addWidget(self.pushButton_accept, 7, 2, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.lineEdit_batchno = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_batchno.setEnabled(False)
        self.lineEdit_batchno.setObjectName("lineEdit_batchno")
        self.gridLayout_2.addWidget(self.lineEdit_batchno, 1, 1, 1, 6)
        self.dateTimeEdit_runstarttime = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit_runstarttime.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(8, 0, 0)))
        self.dateTimeEdit_runstarttime.setCurrentSection(QtWidgets.QDateTimeEdit.YearSection)
        self.dateTimeEdit_runstarttime.setCalendarPopup(True)
        self.dateTimeEdit_runstarttime.setObjectName("dateTimeEdit_runstarttime")
        self.gridLayout_2.addWidget(self.dateTimeEdit_runstarttime, 2, 1, 1, 6)
        self.dateTimeEdit_runendtime = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit_runendtime.setCalendarPopup(True)
        self.dateTimeEdit_runendtime.setObjectName("dateTimeEdit_runendtime")
        self.gridLayout_2.addWidget(self.dateTimeEdit_runendtime, 3, 1, 1, 6)
        self.lineEdit_runtime_day = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_runtime_day.setObjectName("lineEdit_runtime_day")
        self.gridLayout_2.addWidget(self.lineEdit_runtime_day, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 0, 1, 1)
        self.comboBox_runstatus = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_runstatus.setObjectName("comboBox_runstatus")
        self.comboBox_runstatus.addItem("")
        self.comboBox_runstatus.addItem("")
        self.comboBox_runstatus.addItem("")
        self.comboBox_runstatus.addItem("")
        self.comboBox_runstatus.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_runstatus, 5, 1, 1, 6)
        self.lineEdit_remark = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_remark.setObjectName("lineEdit_remark")
        self.gridLayout_2.addWidget(self.lineEdit_remark, 6, 1, 1, 6)
        self.lineEdit_product = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_product.setEnabled(False)
        self.lineEdit_product.setStyleSheet("background-color: rgb(255, 255, 125);")
        self.lineEdit_product.setObjectName("lineEdit_product")
        self.gridLayout_2.addWidget(self.lineEdit_product, 0, 1, 1, 6)
        self.lineEdit_runtime_minute = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_runtime_minute.setObjectName("lineEdit_runtime_minute")
        self.gridLayout_2.addWidget(self.lineEdit_runtime_minute, 4, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 4, 6, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 4, 2, 1, 1)
        self.lineEdit_runtime_hour = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_runtime_hour.setObjectName("lineEdit_runtime_hour")
        self.gridLayout_2.addWidget(self.lineEdit_runtime_hour, 4, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 4, 4, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 4, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_batchno, self.dateTimeEdit_runstarttime)
        Dialog.setTabOrder(self.dateTimeEdit_runstarttime, self.dateTimeEdit_runendtime)
        Dialog.setTabOrder(self.dateTimeEdit_runendtime, self.lineEdit_runtime_day)
        Dialog.setTabOrder(self.lineEdit_runtime_day, self.comboBox_runstatus)
        Dialog.setTabOrder(self.comboBox_runstatus, self.lineEdit_remark)
        Dialog.setTabOrder(self.lineEdit_remark, self.checkBox_1)
        Dialog.setTabOrder(self.checkBox_1, self.checkBox_2)
        Dialog.setTabOrder(self.checkBox_2, self.checkBox_3)
        Dialog.setTabOrder(self.checkBox_3, self.checkBox_4)
        Dialog.setTabOrder(self.checkBox_4, self.checkBox_6)
        Dialog.setTabOrder(self.checkBox_6, self.checkBox_5)
        Dialog.setTabOrder(self.checkBox_5, self.checkBox_7)
        Dialog.setTabOrder(self.checkBox_7, self.checkBox_8)
        Dialog.setTabOrder(self.checkBox_8, self.checkBox_9)
        Dialog.setTabOrder(self.checkBox_9, self.checkBox_10)
        Dialog.setTabOrder(self.checkBox_10, self.comboBox_startstatus)
        Dialog.setTabOrder(self.comboBox_startstatus, self.comboBox_stopstatus)
        Dialog.setTabOrder(self.comboBox_stopstatus, self.pushButton_filler)
        Dialog.setTabOrder(self.pushButton_filler, self.pushButton_accept)
        Dialog.setTabOrder(self.pushButton_accept, self.pushButton_cancel)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_5.setTitle(_translate("Dialog", "运行状态"))
        self.label_3.setText(_translate("Dialog", "开机准备："))
        self.comboBox_startstatus.setItemText(0, _translate("Dialog", "优"))
        self.comboBox_startstatus.setItemText(1, _translate("Dialog", "良"))
        self.comboBox_startstatus.setItemText(2, _translate("Dialog", "中"))
        self.comboBox_startstatus.setItemText(3, _translate("Dialog", "差"))
        self.label_12.setText(_translate("Dialog", "停机保养："))
        self.comboBox_stopstatus.setItemText(0, _translate("Dialog", "优"))
        self.comboBox_stopstatus.setItemText(1, _translate("Dialog", "良"))
        self.comboBox_stopstatus.setItemText(2, _translate("Dialog", "中"))
        self.comboBox_stopstatus.setItemText(3, _translate("Dialog", "差"))
        self.groupBox_3.setTitle(_translate("Dialog", "使用情况"))
        self.checkBox_6.setText(_translate("Dialog", "有松动现象"))
        self.checkBox_4.setText(_translate("Dialog", "有异常震动"))
        self.checkBox_5.setText(_translate("Dialog", "有异常声响"))
        self.checkBox_7.setText(_translate("Dialog", "开关失灵"))
        self.groupBox_2.setTitle(_translate("Dialog", "开机准备"))
        self.checkBox_1.setText(_translate("Dialog", "设备检查"))
        self.checkBox_2.setText(_translate("Dialog", "设备清洁"))
        self.checkBox_3.setText(_translate("Dialog", "系统润滑"))
        self.groupBox_4.setTitle(_translate("Dialog", "停机保养"))
        self.checkBox_8.setText(_translate("Dialog", "设备清洁"))
        self.checkBox_9.setText(_translate("Dialog", "辅助器具清洁"))
        self.checkBox_10.setText(_translate("Dialog", "系统润滑"))
        self.label.setText(_translate("Dialog", "设备："))
        self.label_11.setText(_translate("Dialog", "填写人："))
        self.pushButton_cancel.setText(_translate("Dialog", "取消"))
        self.pushButton_accept.setText(_translate("Dialog", "确定"))
        self.groupBox.setTitle(_translate("Dialog", "运行情况"))
        self.label_4.setText(_translate("Dialog", "产品："))
        self.label_6.setText(_translate("Dialog", "开始运行时间："))
        self.label_10.setText(_translate("Dialog", "备注："))
        self.label_9.setText(_translate("Dialog", "运行情况："))
        self.label_5.setText(_translate("Dialog", "批号："))
        self.label_7.setText(_translate("Dialog", "结束运行时间："))
        self.dateTimeEdit_runstarttime.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd HH:mm"))
        self.dateTimeEdit_runendtime.setDisplayFormat(_translate("Dialog", "yyyy-MM-dd HH:mm"))
        self.label_8.setText(_translate("Dialog", "运行时长："))
        self.comboBox_runstatus.setItemText(0, _translate("Dialog", "正常运行"))
        self.comboBox_runstatus.setItemText(1, _translate("Dialog", "停用待修"))
        self.comboBox_runstatus.setItemText(2, _translate("Dialog", "故障抢修"))
        self.comboBox_runstatus.setItemText(3, _translate("Dialog", "日常小修"))
        self.comboBox_runstatus.setItemText(4, _translate("Dialog", "计划大修"))
        self.label_2.setText(_translate("Dialog", "分钟"))
        self.label_13.setText(_translate("Dialog", "天"))
        self.label_14.setText(_translate("Dialog", "小时"))
from lib.sign.signbutton import SignButton
