# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'equipmentlist.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(781, 585)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidget_deptlist = QtWidgets.QTreeWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_deptlist.sizePolicy().hasHeightForWidth())
        self.treeWidget_deptlist.setSizePolicy(sizePolicy)
        self.treeWidget_deptlist.setObjectName("treeWidget_deptlist")
        self.gridLayout.addWidget(self.treeWidget_deptlist, 0, 0, 1, 1)
        self.treeWidget_equuiplist = QtWidgets.QTreeWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_equuiplist.sizePolicy().hasHeightForWidth())
        self.treeWidget_equuiplist.setSizePolicy(sizePolicy)
        self.treeWidget_equuiplist.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeWidget_equuiplist.setObjectName("treeWidget_equuiplist")
        self.gridLayout.addWidget(self.treeWidget_equuiplist, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.treeWidget_deptlist.headerItem().setText(0, _translate("Form", "部门"))
        self.treeWidget_deptlist.headerItem().setText(1, _translate("Form", "id"))
        self.treeWidget_equuiplist.headerItem().setText(0, _translate("Form", "id"))
        self.treeWidget_equuiplist.headerItem().setText(1, _translate("Form", "类型"))
        self.treeWidget_equuiplist.headerItem().setText(2, _translate("Form", "状态"))
        self.treeWidget_equuiplist.headerItem().setText(3, _translate("Form", "编号"))
        self.treeWidget_equuiplist.headerItem().setText(4, _translate("Form", "名称"))
        self.treeWidget_equuiplist.headerItem().setText(5, _translate("Form", "序列号"))
        self.treeWidget_equuiplist.headerItem().setText(6, _translate("Form", "规格"))
        self.treeWidget_equuiplist.headerItem().setText(7, _translate("Form", "制造商"))
        self.treeWidget_equuiplist.headerItem().setText(8, _translate("Form", "制作日期"))
        self.treeWidget_equuiplist.headerItem().setText(9, _translate("Form", "进厂日期"))
        self.treeWidget_equuiplist.headerItem().setText(10, _translate("Form", "安装位置"))
        self.treeWidget_equuiplist.headerItem().setText(11, _translate("Form", "参数"))
        self.treeWidget_equuiplist.headerItem().setText(12, _translate("Form", "性能"))
