# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userlogin.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(450, 370)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/mainwindowlogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background-color: rgba(230, 230, 230, 230);")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 410, 130))
        self.label_4.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_4.setBaseSize(QtCore.QSize(0, 0))
        self.label_4.setStyleSheet("border-image: url(:/images/logo.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 280, 230, 35))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(17)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("border-image: url(:/images/switch.png);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Label_2 = QtWidgets.QLabel(self.centralwidget)
        self.Label_2.setGeometry(QtCore.QRect(102, 201, 32, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Label_2.setFont(font)
        self.Label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_2.setObjectName("Label_2")
        self.Label = QtWidgets.QLabel(self.centralwidget)
        self.Label.setGeometry(QtCore.QRect(102, 170, 32, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Label.setFont(font)
        self.Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Label.setObjectName("Label")
        self.changepassword = QtWidgets.QLabel(self.centralwidget)
        self.changepassword.setGeometry(QtCore.QRect(102, 250, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(True)
        self.changepassword.setFont(font)
        self.changepassword.setAlignment(QtCore.Qt.AlignCenter)
        self.changepassword.setObjectName("changepassword")
        self.forgetpassword = QtWidgets.QLabel(self.centralwidget)
        self.forgetpassword.setGeometry(QtCore.QRect(210, 250, 60, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(True)
        self.forgetpassword.setFont(font)
        self.forgetpassword.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.forgetpassword.setAlignment(QtCore.Qt.AlignCenter)
        self.forgetpassword.setObjectName("forgetpassword")
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setEnabled(True)
        self.cancel.setGeometry(QtCore.QRect(279, 201, 75, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancel.setFont(font)
        self.cancel.setObjectName("cancel")
        self.enter = QtWidgets.QPushButton(self.centralwidget)
        self.enter.setGeometry(QtCore.QRect(279, 170, 75, 24))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.enter.setFont(font)
        self.enter.setObjectName("enter")
        self.tips = QtWidgets.QLabel(self.centralwidget)
        self.tips.setGeometry(QtCore.QRect(150, 230, 100, 16))
        self.tips.setStyleSheet("color: rgb(255, 85, 0);")
        self.tips.setObjectName("tips")
        self.username = mySignEdit(self.centralwidget)
        self.username.setGeometry(QtCore.QRect(140, 170, 120, 20))
        self.username.setObjectName("username")
        self.label.raise_()
        self.forgetpassword.raise_()
        self.changepassword.raise_()
        self.tips.raise_()
        self.Label_2.raise_()
        self.Label.raise_()
        self.cancel.raise_()
        self.enter.raise_()
        self.label_4.raise_()
        self.username.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.username.username, self.enter)
        MainWindow.setTabOrder(self.enter, self.cancel)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "用户登录"))
        self.label.setText(_translate("MainWindow", "化药普及版"))
        self.Label_2.setText(_translate("MainWindow", "密码"))
        self.Label.setText(_translate("MainWindow", "姓名"))
        self.changepassword.setText(_translate("MainWindow", "修改密码"))
        self.forgetpassword.setText(_translate("MainWindow", "忘记密码"))
        self.cancel.setText(_translate("MainWindow", "取消"))
        self.enter.setText(_translate("MainWindow", "确认"))
        self.tips.setText(_translate("MainWindow", "帐号/密码错误"))
from lib.mywidget.mysignedit import mySignEdit
import userloginimages_rc
