# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clerkdetailUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(810, 570)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 30, 121, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.accept_login = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.accept_login.setChecked(True)
        self.accept_login.setObjectName("accept_login")
        self.verticalLayout_2.addWidget(self.accept_login)
        self.accept_scan = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.accept_scan.setObjectName("accept_scan")
        self.verticalLayout_2.addWidget(self.accept_scan)
        self.change_pwd = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.change_pwd.setObjectName("change_pwd")
        self.verticalLayout_2.addWidget(self.change_pwd)
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName("groupBox_4")
        self.clerk_image = QtWidgets.QLabel(self.groupBox_4)
        self.clerk_image.setGeometry(QtCore.QRect(4, 20, 240, 220))
        self.clerk_image.setStyleSheet("")
        self.clerk_image.setText("")
        self.clerk_image.setObjectName("clerk_image")
        self.setimage = QtWidgets.QPushButton(self.groupBox_4)
        self.setimage.setGeometry(QtCore.QRect(83, 247, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setimage.sizePolicy().hasHeightForWidth())
        self.setimage.setSizePolicy(sizePolicy)
        self.setimage.setObjectName("setimage")
        self.gridLayout_2.addWidget(self.groupBox_4, 1, 2, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 20, 758, 165))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 2, 1, 1)
        self.entranceday = QtWidgets.QLineEdit(self.layoutWidget)
        self.entranceday.setObjectName("entranceday")
        self.gridLayout_3.addWidget(self.entranceday, 4, 1, 1, 1)
        self.schoolname = QtWidgets.QLineEdit(self.layoutWidget)
        self.schoolname.setObjectName("schoolname")
        self.gridLayout_3.addWidget(self.schoolname, 5, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 5, 0, 1, 1)
        self.marrystatus = QtWidgets.QComboBox(self.layoutWidget)
        self.marrystatus.setEditable(False)
        self.marrystatus.setObjectName("marrystatus")
        self.marrystatus.addItem("")
        self.marrystatus.addItem("")
        self.gridLayout_3.addWidget(self.marrystatus, 1, 5, 1, 1)
        self.policystatus = QtWidgets.QComboBox(self.layoutWidget)
        self.policystatus.setEditable(True)
        self.policystatus.setObjectName("policystatus")
        self.policystatus.addItem("")
        self.policystatus.addItem("")
        self.gridLayout_3.addWidget(self.policystatus, 2, 5, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 4, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 3, 2, 1, 1)
        self.sex = QtWidgets.QComboBox(self.layoutWidget)
        self.sex.setObjectName("sex")
        self.sex.addItem("")
        self.sex.addItem("")
        self.gridLayout_3.addWidget(self.sex, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.idno = QtWidgets.QLineEdit(self.layoutWidget)
        self.idno.setObjectName("idno")
        self.gridLayout_3.addWidget(self.idno, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.clerkid = QtWidgets.QLineEdit(self.layoutWidget)
        self.clerkid.setObjectName("clerkid")
        self.gridLayout_3.addWidget(self.clerkid, 0, 1, 1, 1)
        self.clerkname = QtWidgets.QLineEdit(self.layoutWidget)
        self.clerkname.setObjectName("clerkname")
        self.gridLayout_3.addWidget(self.clerkname, 0, 3, 1, 1)
        self.inputcode = QtWidgets.QLineEdit(self.layoutWidget)
        self.inputcode.setObjectName("inputcode")
        self.gridLayout_3.addWidget(self.inputcode, 0, 5, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 2, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 3, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 4, 4, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 5, 4, 1, 1)
        self.telno = QtWidgets.QLineEdit(self.layoutWidget)
        self.telno.setObjectName("telno")
        self.gridLayout_3.addWidget(self.telno, 3, 5, 1, 1)
        self.special = QtWidgets.QLineEdit(self.layoutWidget)
        self.special.setObjectName("special")
        self.gridLayout_3.addWidget(self.special, 4, 5, 1, 1)
        self.strongsuit = QtWidgets.QLineEdit(self.layoutWidget)
        self.strongsuit.setObjectName("strongsuit")
        self.gridLayout_3.addWidget(self.strongsuit, 5, 5, 1, 1)
        self.birthday = QtWidgets.QLineEdit(self.layoutWidget)
        self.birthday.setObjectName("birthday")
        self.gridLayout_3.addWidget(self.birthday, 1, 3, 1, 1)
        self.native_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.native_2.setObjectName("native_2")
        self.gridLayout_3.addWidget(self.native_2, 2, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 5, 2, 1, 1)
        self.address = QtWidgets.QLineEdit(self.layoutWidget)
        self.address.setObjectName("address")
        self.gridLayout_3.addWidget(self.address, 3, 3, 1, 1)
        self.edudegree = QtWidgets.QComboBox(self.layoutWidget)
        self.edudegree.setEditable(True)
        self.edudegree.setObjectName("edudegree")
        self.gridLayout_3.addWidget(self.edudegree, 4, 3, 1, 1)
        self.techtitle = QtWidgets.QComboBox(self.layoutWidget)
        self.techtitle.setEditable(True)
        self.techtitle.setObjectName("techtitle")
        self.gridLayout_3.addWidget(self.techtitle, 5, 3, 1, 1)
        self.nation = QtWidgets.QComboBox(self.layoutWidget)
        self.nation.setEditable(True)
        self.nation.setObjectName("nation")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.nation.addItem("")
        self.gridLayout_3.addWidget(self.nation, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 1, 3)
        self.accept = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accept.sizePolicy().hasHeightForWidth())
        self.accept.setSizePolicy(sizePolicy)
        self.accept.setObjectName("accept")
        self.gridLayout_2.addWidget(self.accept, 2, 1, 1, 1, QtCore.Qt.AlignRight)
        self.cancel = QtWidgets.QPushButton(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel.sizePolicy().hasHeightForWidth())
        self.cancel.setSizePolicy(sizePolicy)
        self.cancel.setObjectName("cancel")
        self.gridLayout_2.addWidget(self.cancel, 2, 2, 1, 1, QtCore.Qt.AlignLeft)
        self.groupBox = QtWidgets.QGroupBox(self.tab_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 20, 371, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cbchbox_4 = ComboCheckBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbchbox_4.sizePolicy().hasHeightForWidth())
        self.cbchbox_4.setSizePolicy(sizePolicy)
        self.cbchbox_4.setStyleSheet("border:none;\n"
"background: none;")
        self.cbchbox_4.setObjectName("cbchbox_4")
        self.gridLayout_4.addWidget(self.cbchbox_4, 1, 0, 1, 1)
        self.cbchbox_3 = ComboCheckBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbchbox_3.sizePolicy().hasHeightForWidth())
        self.cbchbox_3.setSizePolicy(sizePolicy)
        self.cbchbox_3.setStyleSheet("border:none;\n"
"background: none;")
        self.cbchbox_3.setObjectName("cbchbox_3")
        self.gridLayout_4.addWidget(self.cbchbox_3, 0, 2, 1, 1)
        self.cbchbox_1 = ComboCheckBox(self.gridLayoutWidget)
        self.cbchbox_1.setStyleSheet("border:none;\n"
"background: none;")
        self.cbchbox_1.setObjectName("cbchbox_1")
        self.gridLayout_4.addWidget(self.cbchbox_1, 0, 0, 1, 1)
        self.cbchbox_2 = ComboCheckBox(self.gridLayoutWidget)
        self.cbchbox_2.setStyleSheet("border:none;\n"
"background: none;")
        self.cbchbox_2.setObjectName("cbchbox_2")
        self.gridLayout_4.addWidget(self.cbchbox_2, 0, 1, 1, 1)
        self.cbchbox_5 = ComboCheckBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbchbox_5.sizePolicy().hasHeightForWidth())
        self.cbchbox_5.setSizePolicy(sizePolicy)
        self.cbchbox_5.setStyleSheet("border:none;\n"
"background: none;")
        self.cbchbox_5.setObjectName("cbchbox_5")
        self.gridLayout_4.addWidget(self.cbchbox_5, 1, 1, 1, 1)
        self.cbchbox_6 = ComboCheckBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbchbox_6.sizePolicy().hasHeightForWidth())
        self.cbchbox_6.setSizePolicy(sizePolicy)
        self.cbchbox_6.setStyleSheet("border:none;\n"
"background: none;")
        self.cbchbox_6.setObjectName("cbchbox_6")
        self.gridLayout_4.addWidget(self.cbchbox_6, 1, 2, 1, 1)
        self.cbchbox_9 = ComboCheckBox(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbchbox_9.sizePolicy().hasHeightForWidth())
        self.cbchbox_9.setSizePolicy(sizePolicy)
        self.cbchbox_9.setStyleSheet("border:none;\n"
"background: none;")
        self.cbchbox_9.setObjectName("cbchbox_9")
        self.gridLayout_4.addWidget(self.cbchbox_9, 2, 2, 1, 1)
        self.cbchbox_7 = ComboCheckBox(self.gridLayoutWidget)
        self.cbchbox_7.setStyleSheet("border:none;\n"
"background: none;")
        self.cbchbox_7.setObjectName("cbchbox_7")
        self.gridLayout_4.addWidget(self.cbchbox_7, 2, 0, 1, 1)
        self.cbchbox_8 = ComboCheckBox(self.gridLayoutWidget)
        self.cbchbox_8.setStyleSheet("border:none;\n"
"background: none;")
        self.cbchbox_8.setObjectName("cbchbox_8")
        self.gridLayout_4.addWidget(self.cbchbox_8, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 2, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setGeometry(QtCore.QRect(10, 30, 54, 22))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.toolButton = QtWidgets.QToolButton(self.groupBox_5)
        self.toolButton.setGeometry(QtCore.QRect(180, 30, 41, 21))
        self.toolButton.setObjectName("toolButton")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_4.setGeometry(QtCore.QRect(70, 30, 113, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        self.label_21.setGeometry(QtCore.QRect(10, 70, 54, 22))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_2.setGeometry(QtCore.QRect(70, 70, 101, 22))
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_4.setGeometry(QtCore.QRect(184, 70, 60, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.treeWidget_4 = QtWidgets.QTreeWidget(self.groupBox_5)
        self.treeWidget_4.setGeometry(QtCore.QRect(0, 110, 251, 401))
        self.treeWidget_4.setObjectName("treeWidget_4")
        self.lineEdit_4.raise_()
        self.label_20.raise_()
        self.toolButton.raise_()
        self.label_21.raise_()
        self.comboBox_2.raise_()
        self.pushButton_4.raise_()
        self.treeWidget_4.raise_()
        self.horizontalLayout.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setObjectName("groupBox_6")
        self.treeWidget = QtWidgets.QTreeWidget(self.groupBox_6)
        self.treeWidget.setGeometry(QtCore.QRect(5, 20, 491, 481))
        self.treeWidget.setObjectName("treeWidget")
        self.horizontalLayout.addWidget(self.groupBox_6)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 771, 521))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.tabWidget_2.addTab(self.tab_11, "")
        self.tab_21 = QtWidgets.QWidget()
        self.tab_21.setObjectName("tab_21")
        self.treeWidget_2 = QtWidgets.QTreeWidget(self.tab_21)
        self.treeWidget_2.setGeometry(QtCore.QRect(0, 0, 761, 501))
        self.treeWidget_2.setObjectName("treeWidget_2")
        self.tabWidget_2.addTab(self.tab_21, "")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 0, 771, 521))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.treeWidget_3 = QtWidgets.QTreeWidget(self.tab_8)
        self.treeWidget_3.setGeometry(QtCore.QRect(0, 0, 761, 501))
        self.treeWidget_3.setObjectName("treeWidget_3")
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget_3.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_3.setTitle(_translate("Dialog", "其他"))
        self.accept_login.setText(_translate("Dialog", "允许密码登录"))
        self.accept_scan.setText(_translate("Dialog", "允许扫码登录"))
        self.change_pwd.setText(_translate("Dialog", "定期修改密码"))
        self.groupBox_4.setTitle(_translate("Dialog", "相片"))
        self.setimage.setText(_translate("Dialog", "获取图片"))
        self.groupBox_2.setTitle(_translate("Dialog", "基本情况"))
        self.label_5.setText(_translate("Dialog", "出生日期："))
        self.label_4.setText(_translate("Dialog", "性别："))
        self.label_10.setText(_translate("Dialog", "毕业学校："))
        self.marrystatus.setItemText(0, _translate("Dialog", "未婚"))
        self.marrystatus.setItemText(1, _translate("Dialog", "已婚"))
        self.policystatus.setItemText(0, _translate("Dialog", "群众"))
        self.policystatus.setItemText(1, _translate("Dialog", "党员"))
        self.label_11.setText(_translate("Dialog", "籍贯："))
        self.label_6.setText(_translate("Dialog", "婚姻状况："))
        self.label_13.setText(_translate("Dialog", "文化程度："))
        self.label_2.setText(_translate("Dialog", "姓名："))
        self.label_12.setText(_translate("Dialog", "家庭地址："))
        self.sex.setItemText(0, _translate("Dialog", "男"))
        self.sex.setItemText(1, _translate("Dialog", "女"))
        self.label_8.setText(_translate("Dialog", "身份证证号码："))
        self.label.setText(_translate("Dialog", "编号："))
        self.label_9.setText(_translate("Dialog", "雇佣日期："))
        self.label_3.setText(_translate("Dialog", "输入码："))
        self.label_7.setText(_translate("Dialog", "民族："))
        self.label_15.setText(_translate("Dialog", "政治面貌："))
        self.label_16.setText(_translate("Dialog", "联系电话："))
        self.label_17.setText(_translate("Dialog", "专业："))
        self.label_18.setText(_translate("Dialog", "入职前工作年限："))
        self.label_14.setText(_translate("Dialog", "职称："))
        self.nation.setItemText(0, _translate("Dialog", "汉族"))
        self.nation.setItemText(1, _translate("Dialog", "傣族"))
        self.nation.setItemText(2, _translate("Dialog", "壮族"))
        self.nation.setItemText(3, _translate("Dialog", "回族"))
        self.nation.setItemText(4, _translate("Dialog", "满族"))
        self.nation.setItemText(5, _translate("Dialog", "苗族"))
        self.nation.setItemText(6, _translate("Dialog", "彝族"))
        self.nation.setItemText(7, _translate("Dialog", "藏族"))
        self.nation.setItemText(8, _translate("Dialog", "侗族"))
        self.nation.setItemText(9, _translate("Dialog", "瑶族"))
        self.nation.setItemText(10, _translate("Dialog", "白族"))
        self.nation.setItemText(11, _translate("Dialog", "黎族"))
        self.nation.setItemText(12, _translate("Dialog", "畲族"))
        self.nation.setItemText(13, _translate("Dialog", "佤族"))
        self.nation.setItemText(14, _translate("Dialog", "水族"))
        self.nation.setItemText(15, _translate("Dialog", "羌族"))
        self.nation.setItemText(16, _translate("Dialog", "土族"))
        self.nation.setItemText(17, _translate("Dialog", "怒族"))
        self.nation.setItemText(18, _translate("Dialog", "京族"))
        self.nation.setItemText(19, _translate("Dialog", "土家族"))
        self.nation.setItemText(20, _translate("Dialog", "蒙古族"))
        self.nation.setItemText(21, _translate("Dialog", "布依族"))
        self.nation.setItemText(22, _translate("Dialog", "朝鲜族"))
        self.nation.setItemText(23, _translate("Dialog", "哈尼族"))
        self.nation.setItemText(24, _translate("Dialog", "傈僳族"))
        self.nation.setItemText(25, _translate("Dialog", "东乡族"))
        self.nation.setItemText(26, _translate("Dialog", "仡佬族"))
        self.nation.setItemText(27, _translate("Dialog", "拉祜族"))
        self.nation.setItemText(28, _translate("Dialog", "纳西族"))
        self.nation.setItemText(29, _translate("Dialog", "仫佬族"))
        self.nation.setItemText(30, _translate("Dialog", "锡伯族"))
        self.nation.setItemText(31, _translate("Dialog", "景颇族"))
        self.nation.setItemText(32, _translate("Dialog", "撒拉族"))
        self.nation.setItemText(33, _translate("Dialog", "布朗族"))
        self.nation.setItemText(34, _translate("Dialog", "毛南族"))
        self.nation.setItemText(35, _translate("Dialog", "普米族"))
        self.nation.setItemText(36, _translate("Dialog", "阿昌族"))
        self.nation.setItemText(37, _translate("Dialog", "基诺族"))
        self.nation.setItemText(38, _translate("Dialog", "德昂族"))
        self.nation.setItemText(39, _translate("Dialog", "保安族"))
        self.nation.setItemText(40, _translate("Dialog", "裕固族"))
        self.nation.setItemText(41, _translate("Dialog", "门巴族"))
        self.nation.setItemText(42, _translate("Dialog", "独龙族"))
        self.nation.setItemText(43, _translate("Dialog", "赫哲族"))
        self.nation.setItemText(44, _translate("Dialog", "高山族"))
        self.nation.setItemText(45, _translate("Dialog", "珞巴族"))
        self.nation.setItemText(46, _translate("Dialog", "塔吉克族"))
        self.nation.setItemText(47, _translate("Dialog", "哈萨克族"))
        self.nation.setItemText(48, _translate("Dialog", "鄂温克族"))
        self.nation.setItemText(49, _translate("Dialog", "达斡尔族"))
        self.nation.setItemText(50, _translate("Dialog", "俄罗斯族"))
        self.nation.setItemText(51, _translate("Dialog", "鄂伦春族"))
        self.nation.setItemText(52, _translate("Dialog", "塔塔尔族 "))
        self.nation.setItemText(53, _translate("Dialog", "维吾尔族"))
        self.nation.setItemText(54, _translate("Dialog", "乌孜别克族"))
        self.nation.setItemText(55, _translate("Dialog", "柯尔克孜族"))
        self.accept.setText(_translate("Dialog", "确认"))
        self.cancel.setText(_translate("Dialog", "取消"))
        self.groupBox.setTitle(_translate("Dialog", "人员权限"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Dialog", "基本资料"))
        self.groupBox_5.setTitle(_translate("Dialog", "所在部门"))
        self.label_20.setText(_translate("Dialog", "部门："))
        self.toolButton.setText(_translate("Dialog", "..."))
        self.label_21.setText(_translate("Dialog", "职务："))
        self.pushButton_4.setText(_translate("Dialog", "确定"))
        self.treeWidget_4.headerItem().setText(0, _translate("Dialog", "编号"))
        self.treeWidget_4.headerItem().setText(1, _translate("Dialog", "部门名称"))
        self.treeWidget_4.headerItem().setText(2, _translate("Dialog", "职务"))
        self.treeWidget_4.headerItem().setText(3, _translate("Dialog", "默认部门"))
        self.groupBox_6.setTitle(_translate("Dialog", "人员经历"))
        self.treeWidget.headerItem().setText(0, _translate("Dialog", "类别"))
        self.treeWidget.headerItem().setText(1, _translate("Dialog", "起始日期"))
        self.treeWidget.headerItem().setText(2, _translate("Dialog", "终止日期"))
        self.treeWidget.headerItem().setText(3, _translate("Dialog", "单位"))
        self.treeWidget.headerItem().setText(4, _translate("Dialog", "经历"))
        self.treeWidget.headerItem().setText(5, _translate("Dialog", "单位"))
        self.treeWidget.headerItem().setText(6, _translate("Dialog", "职务"))
        self.treeWidget.headerItem().setText(7, _translate("Dialog", "备注"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "所在部门及经历"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_11), _translate("Dialog", "编辑"))
        self.treeWidget_2.headerItem().setText(0, _translate("Dialog", "起始日期"))
        self.treeWidget_2.headerItem().setText(1, _translate("Dialog", "终止日期"))
        self.treeWidget_2.headerItem().setText(2, _translate("Dialog", "培训内容"))
        self.treeWidget_2.headerItem().setText(3, _translate("Dialog", "授课时间"))
        self.treeWidget_2.headerItem().setText(4, _translate("Dialog", "授课人"))
        self.treeWidget_2.headerItem().setText(5, _translate("Dialog", "成绩"))
        self.treeWidget_2.headerItem().setText(6, _translate("Dialog", "授课地点"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_21), _translate("Dialog", "提交"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "培训记录"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("Dialog", "编辑"))
        self.treeWidget_3.headerItem().setText(0, _translate("Dialog", "日期"))
        self.treeWidget_3.headerItem().setText(1, _translate("Dialog", "检查项目"))
        self.treeWidget_3.headerItem().setText(2, _translate("Dialog", "体检单位"))
        self.treeWidget_3.headerItem().setText(3, _translate("Dialog", "健康状况"))
        self.treeWidget_3.headerItem().setText(4, _translate("Dialog", "备注"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("Dialog", "提交"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "体检记录"))
from lib.combocheckbox import ComboCheckBox
