# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modifydeptmentUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.deptId = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deptId.sizePolicy().hasHeightForWidth())
        self.deptId.setSizePolicy(sizePolicy)
        self.deptId.setObjectName("deptId")
        self.gridLayout.addWidget(self.deptId, 0, 2, 1, 1)
        self.inputCode = QtWidgets.QLineEdit(Dialog)
        self.inputCode.setObjectName("inputCode")
        self.gridLayout.addWidget(self.inputCode, 3, 2, 1, 1)
        self.authority5 = QtWidgets.QCheckBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authority5.sizePolicy().hasHeightForWidth())
        self.authority5.setSizePolicy(sizePolicy)
        self.authority5.setObjectName("authority5")
        self.gridLayout.addWidget(self.authority5, 5, 2, 1, 1)
        self.cancel = QtWidgets.QPushButton(Dialog)
        self.cancel.setObjectName("cancel")
        self.gridLayout.addWidget(self.cancel, 10, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 3, 1, 1)
        self.deptNameLabel = QtWidgets.QLabel(Dialog)
        self.deptNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.deptNameLabel.setObjectName("deptNameLabel")
        self.gridLayout.addWidget(self.deptNameLabel, 1, 1, 1, 1)
        self.authority8 = QtWidgets.QCheckBox(Dialog)
        self.authority8.setObjectName("authority8")
        self.gridLayout.addWidget(self.authority8, 8, 2, 1, 1)
        self.authority1 = QtWidgets.QCheckBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.authority1.sizePolicy().hasHeightForWidth())
        self.authority1.setSizePolicy(sizePolicy)
        self.authority1.setObjectName("authority1")
        self.gridLayout.addWidget(self.authority1, 5, 1, 1, 1)
        self.parentNameLabel = QtWidgets.QLabel(Dialog)
        self.parentNameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.parentNameLabel.setObjectName("parentNameLabel")
        self.gridLayout.addWidget(self.parentNameLabel, 2, 1, 1, 1)
        self.parentName = QtWidgets.QComboBox(Dialog)
        self.parentName.setEditable(True)
        self.parentName.setObjectName("parentName")
        self.gridLayout.addWidget(self.parentName, 2, 2, 1, 1)
        self.authority2 = QtWidgets.QCheckBox(Dialog)
        self.authority2.setObjectName("authority2")
        self.gridLayout.addWidget(self.authority2, 6, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)
        self.authority7 = QtWidgets.QCheckBox(Dialog)
        self.authority7.setObjectName("authority7")
        self.gridLayout.addWidget(self.authority7, 7, 2, 1, 1)
        self.deptName = QtWidgets.QLineEdit(Dialog)
        self.deptName.setObjectName("deptName")
        self.gridLayout.addWidget(self.deptName, 1, 2, 1, 1)
        self.accept = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accept.sizePolicy().hasHeightForWidth())
        self.accept.setSizePolicy(sizePolicy)
        self.accept.setObjectName("accept")
        self.gridLayout.addWidget(self.accept, 10, 1, 1, 1)
        self.inputCdeLabel = QtWidgets.QLabel(Dialog)
        self.inputCdeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.inputCdeLabel.setObjectName("inputCdeLabel")
        self.gridLayout.addWidget(self.inputCdeLabel, 3, 1, 1, 1)
        self.deptIdLabel = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deptIdLabel.sizePolicy().hasHeightForWidth())
        self.deptIdLabel.setSizePolicy(sizePolicy)
        self.deptIdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.deptIdLabel.setObjectName("deptIdLabel")
        self.gridLayout.addWidget(self.deptIdLabel, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 1, 1, 1)
        self.authority6 = QtWidgets.QCheckBox(Dialog)
        self.authority6.setObjectName("authority6")
        self.gridLayout.addWidget(self.authority6, 6, 2, 1, 1)
        self.deptIdtips = QtWidgets.QLabel(Dialog)
        self.deptIdtips.setStyleSheet("color: rgb(255, 0, 0);")
        self.deptIdtips.setObjectName("deptIdtips")
        self.gridLayout.addWidget(self.deptIdtips, 0, 3, 1, 1)
        self.parentNametips = QtWidgets.QLabel(Dialog)
        self.parentNametips.setStyleSheet("color: rgb(255, 0, 0);")
        self.parentNametips.setObjectName("parentNametips")
        self.gridLayout.addWidget(self.parentNametips, 2, 3, 1, 1)
        self.deptNametips = QtWidgets.QLabel(Dialog)
        self.deptNametips.setStyleSheet("color: rgb(255, 0, 0);")
        self.deptNametips.setObjectName("deptNametips")
        self.gridLayout.addWidget(self.deptNametips, 1, 3, 1, 1)
        self.authority3 = QtWidgets.QCheckBox(Dialog)
        self.authority3.setObjectName("authority3")
        self.gridLayout.addWidget(self.authority3, 7, 1, 1, 1)
        self.authority4 = QtWidgets.QCheckBox(Dialog)
        self.authority4.setObjectName("authority4")
        self.gridLayout.addWidget(self.authority4, 8, 1, 1, 1)
        self.deptNameLabel.setBuddy(self.deptName)
        self.parentNameLabel.setBuddy(self.parentName)
        self.inputCdeLabel.setBuddy(self.inputCode)
        self.deptIdLabel.setBuddy(self.deptId)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.deptId, self.deptName)
        Dialog.setTabOrder(self.deptName, self.parentName)
        Dialog.setTabOrder(self.parentName, self.inputCode)
        Dialog.setTabOrder(self.inputCode, self.authority1)
        Dialog.setTabOrder(self.authority1, self.authority2)
        Dialog.setTabOrder(self.authority2, self.authority5)
        Dialog.setTabOrder(self.authority5, self.authority6)
        Dialog.setTabOrder(self.authority6, self.authority7)
        Dialog.setTabOrder(self.authority7, self.authority8)
        Dialog.setTabOrder(self.authority8, self.accept)
        Dialog.setTabOrder(self.accept, self.cancel)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "修改部门资料"))
        self.authority5.setText(_translate("Dialog", "采购部门"))
        self.cancel.setText(_translate("Dialog", "取消"))
        self.deptNameLabel.setText(_translate("Dialog", "部门名称"))
        self.authority8.setText(_translate("Dialog", "财务"))
        self.authority1.setText(_translate("Dialog", "行政部门"))
        self.parentNameLabel.setText(_translate("Dialog", "上级部门"))
        self.authority2.setText(_translate("Dialog", "仓库"))
        self.authority7.setText(_translate("Dialog", "质控管理"))
        self.accept.setText(_translate("Dialog", "确认"))
        self.inputCdeLabel.setText(_translate("Dialog", "快速输入码"))
        self.deptIdLabel.setText(_translate("Dialog", "部门编号"))
        self.label_5.setText(_translate("Dialog", "部门类型"))
        self.authority6.setText(_translate("Dialog", "生产车间"))
        self.deptIdtips.setText(_translate("Dialog", "部门编号不能为空"))
        self.parentNametips.setText(_translate("Dialog", "不存在该上级部门"))
        self.deptNametips.setText(_translate("Dialog", "部门名称不能为空"))
        self.authority3.setText(_translate("Dialog", "销售业务"))
        self.authority4.setText(_translate("Dialog", "设备管理"))
