# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qrcodelist.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1004, 608)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidget_qrcode = QtWidgets.QTreeWidget(Form)
        self.treeWidget_qrcode.setObjectName("treeWidget_qrcode")
        self.treeWidget_qrcode.header().setVisible(False)
        self.gridLayout.addWidget(self.treeWidget_qrcode, 0, 0, 1, 3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_scanqrcode = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_scanqrcode.sizePolicy().hasHeightForWidth())
        self.pushButton_scanqrcode.setSizePolicy(sizePolicy)
        self.pushButton_scanqrcode.setObjectName("pushButton_scanqrcode")
        self.horizontalLayout.addWidget(self.pushButton_scanqrcode)
        self.pushButton_deleteqrcode = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_deleteqrcode.sizePolicy().hasHeightForWidth())
        self.pushButton_deleteqrcode.setSizePolicy(sizePolicy)
        self.pushButton_deleteqrcode.setObjectName("pushButton_deleteqrcode")
        self.horizontalLayout.addWidget(self.pushButton_deleteqrcode)
        self.pushButtonchangeqrcode = QtWidgets.QPushButton(Form)
        self.pushButtonchangeqrcode.setObjectName("pushButtonchangeqrcode")
        self.horizontalLayout.addWidget(self.pushButtonchangeqrcode)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.treeWidget_qrcode.headerItem().setText(0, _translate("Form", "id"))
        self.treeWidget_qrcode.headerItem().setText(1, _translate("Form", "二维码"))
        self.treeWidget_qrcode.headerItem().setText(2, _translate("Form", "级别"))
        self.pushButton_scanqrcode.setText(_translate("Form", "输入二维码"))
        self.pushButton_deleteqrcode.setText(_translate("Form", "删除二维码"))
        self.pushButtonchangeqrcode.setText(_translate("Form", "替换二维码"))
