# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modifystuffparmeter.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(462, 240)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_location = QtWidgets.QComboBox(Dialog)
        self.comboBox_location.setEditable(True)
        self.comboBox_location.setObjectName("comboBox_location")
        self.gridLayout.addWidget(self.comboBox_location, 4, 1, 1, 1)
        self.lineEdit_rdensity = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_rdensity.setObjectName("lineEdit_rdensity")
        self.gridLayout.addWidget(self.lineEdit_rdensity, 2, 1, 1, 1)
        self.lineEdit_impurity = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_impurity.setObjectName("lineEdit_impurity")
        self.gridLayout.addWidget(self.lineEdit_impurity, 3, 1, 1, 1)
        self.lineEdit_water = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_water.setObjectName("lineEdit_water")
        self.gridLayout.addWidget(self.lineEdit_water, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_accept = QtWidgets.QPushButton(Dialog)
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.horizontalLayout.addWidget(self.pushButton_accept)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 2)
        self.lineEdit_content = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_content.setObjectName("lineEdit_content")
        self.gridLayout.addWidget(self.lineEdit_content, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_contentunit = QtWidgets.QLabel(Dialog)
        self.label_contentunit.setText("")
        self.label_contentunit.setObjectName("label_contentunit")
        self.gridLayout.addWidget(self.label_contentunit, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_content, self.lineEdit_water)
        Dialog.setTabOrder(self.lineEdit_water, self.lineEdit_rdensity)
        Dialog.setTabOrder(self.lineEdit_rdensity, self.lineEdit_impurity)
        Dialog.setTabOrder(self.lineEdit_impurity, self.comboBox_location)
        Dialog.setTabOrder(self.comboBox_location, self.pushButton_accept)
        Dialog.setTabOrder(self.pushButton_accept, self.pushButton_cancel)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "编辑物料入库信息"))
        self.pushButton_accept.setText(_translate("Dialog", "确认"))
        self.pushButton_cancel.setText(_translate("Dialog", "取消"))
        self.label_4.setText(_translate("Dialog", "杂质："))
        self.label_2.setText(_translate("Dialog", "水分："))
        self.label_3.setText(_translate("Dialog", "相对密度："))
        self.label.setText(_translate("Dialog", "含量："))
        self.label_5.setText(_translate("Dialog", "存放位置："))
        self.label_7.setText(_translate("Dialog", "%"))
