# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'productrepository.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(828, 554)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton_batchno = QtWidgets.QRadioButton(Form)
        self.radioButton_batchno.setChecked(True)
        self.radioButton_batchno.setObjectName("radioButton_batchno")
        self.horizontalLayout.addWidget(self.radioButton_batchno)
        self.radioButton_kind = QtWidgets.QRadioButton(Form)
        self.radioButton_kind.setObjectName("radioButton_kind")
        self.horizontalLayout.addWidget(self.radioButton_kind)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.treeWidget_productbatchnolist = QtWidgets.QTreeWidget(Form)
        self.treeWidget_productbatchnolist.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeWidget_productbatchnolist.setObjectName("treeWidget_productbatchnolist")
        self.gridLayout.addWidget(self.treeWidget_productbatchnolist, 3, 0, 1, 1)
        self.treeWidget_productkindlist = QtWidgets.QTreeWidget(Form)
        self.treeWidget_productkindlist.setObjectName("treeWidget_productkindlist")
        self.gridLayout.addWidget(self.treeWidget_productkindlist, 4, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.radioButton_batchno.setText(_translate("Form", "按产品批次排序"))
        self.radioButton_kind.setText(_translate("Form", "按产品类别排序"))
        self.treeWidget_productbatchnolist.headerItem().setText(0, _translate("Form", "id"))
        self.treeWidget_productbatchnolist.headerItem().setText(1, _translate("Form", "状态"))
        self.treeWidget_productbatchnolist.headerItem().setText(2, _translate("Form", "产品"))
        self.treeWidget_productbatchnolist.headerItem().setText(3, _translate("Form", "种类"))
        self.treeWidget_productbatchnolist.headerItem().setText(4, _translate("Form", "批号"))
        self.treeWidget_productbatchnolist.headerItem().setText(5, _translate("Form", "含量规格"))
        self.treeWidget_productbatchnolist.headerItem().setText(6, _translate("Form", "包装规格"))
        self.treeWidget_productbatchnolist.headerItem().setText(7, _translate("Form", "入库数量"))
        self.treeWidget_productbatchnolist.headerItem().setText(8, _translate("Form", "剩余库存"))
        self.treeWidget_productbatchnolist.headerItem().setText(9, _translate("Form", "单位"))
        self.treeWidget_productbatchnolist.headerItem().setText(10, _translate("Form", "存放位置"))
        self.treeWidget_productbatchnolist.headerItem().setText(11, _translate("Form", "入库日期"))
        self.treeWidget_productbatchnolist.headerItem().setText(12, _translate("Form", "生产日期"))
        self.treeWidget_productbatchnolist.headerItem().setText(13, _translate("Form", "过期日期"))
        self.treeWidget_productbatchnolist.headerItem().setText(14, _translate("Form", "仓管员"))
        self.treeWidget_productkindlist.headerItem().setText(0, _translate("Form", "产品"))
        self.treeWidget_productkindlist.headerItem().setText(1, _translate("Form", "种类"))
        self.treeWidget_productkindlist.headerItem().setText(2, _translate("Form", "含量规格"))
        self.treeWidget_productkindlist.headerItem().setText(3, _translate("Form", "包装规格"))
        self.treeWidget_productkindlist.headerItem().setText(4, _translate("Form", "入库数量"))
        self.treeWidget_productkindlist.headerItem().setText(5, _translate("Form", "剩余库存"))
        self.treeWidget_productkindlist.headerItem().setText(6, _translate("Form", "单位"))
