# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'purstuffcheckin.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(828, 574)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidget_stufflist = QtWidgets.QTreeWidget(Form)
        self.treeWidget_stufflist.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeWidget_stufflist.setObjectName("treeWidget_stufflist")
        self.gridLayout.addWidget(self.treeWidget_stufflist, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.treeWidget_stufflist.headerItem().setText(0, _translate("Form", "id"))
        self.treeWidget_stufflist.headerItem().setText(1, _translate("Form", "lrid"))
        self.treeWidget_stufflist.headerItem().setText(2, _translate("Form", "类别"))
        self.treeWidget_stufflist.headerItem().setText(3, _translate("Form", "物料"))
        self.treeWidget_stufflist.headerItem().setText(4, _translate("Form", "进厂批号"))
        self.treeWidget_stufflist.headerItem().setText(5, _translate("Form", "厂家批号"))
        self.treeWidget_stufflist.headerItem().setText(6, _translate("Form", "含量规格"))
        self.treeWidget_stufflist.headerItem().setText(7, _translate("Form", "包装规格"))
        self.treeWidget_stufflist.headerItem().setText(8, _translate("Form", "入库数量"))
        self.treeWidget_stufflist.headerItem().setText(9, _translate("Form", "单位"))
        self.treeWidget_stufflist.headerItem().setText(10, _translate("Form", "供应商"))
        self.treeWidget_stufflist.headerItem().setText(11, _translate("Form", "生产厂家"))
