# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scanppopqrcode.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(725, 405)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEdit_qrcode = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit_qrcode.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit_qrcode.sizePolicy().hasHeightForWidth())
        self.plainTextEdit_qrcode.setSizePolicy(sizePolicy)
        self.plainTextEdit_qrcode.setFocusPolicy(QtCore.Qt.NoFocus)
        self.plainTextEdit_qrcode.setObjectName("plainTextEdit_qrcode")
        self.gridLayout.addWidget(self.plainTextEdit_qrcode, 1, 0, 1, 5)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_accept = QtWidgets.QPushButton(Dialog)
        self.pushButton_accept.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_accept.setAutoDefault(False)
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.horizontalLayout.addWidget(self.pushButton_accept)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cancel.sizePolicy().hasHeightForWidth())
        self.pushButton_cancel.setSizePolicy(sizePolicy)
        self.pushButton_cancel.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton_cancel.setAutoDefault(False)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 5)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plainTextEdit_errormsg = QtWidgets.QPlainTextEdit(self.groupBox)
        self.plainTextEdit_errormsg.setEnabled(True)
        self.plainTextEdit_errormsg.setFocusPolicy(QtCore.Qt.NoFocus)
        self.plainTextEdit_errormsg.setPlainText("")
        self.plainTextEdit_errormsg.setObjectName("plainTextEdit_errormsg")
        self.gridLayout_2.addWidget(self.plainTextEdit_errormsg, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 1, 5)
        self.radioButton_0 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_0.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_0.setChecked(True)
        self.radioButton_0.setObjectName("radioButton_0")
        self.gridLayout.addWidget(self.radioButton_0, 3, 0, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 3, 1, 1, 1)
        self.radioButton_1 = QtWidgets.QRadioButton(Dialog)
        self.radioButton_1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.radioButton_1.setObjectName("radioButton_1")
        self.gridLayout.addWidget(self.radioButton_1, 3, 2, 1, 1)
        self.lineEdit_qrcode = myQrcodeLineEdit(Dialog)
        self.lineEdit_qrcode.setObjectName("lineEdit_qrcode")
        self.gridLayout.addWidget(self.lineEdit_qrcode, 0, 1, 1, 4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_qrcode, self.plainTextEdit_qrcode)
        Dialog.setTabOrder(self.plainTextEdit_qrcode, self.plainTextEdit_errormsg)
        Dialog.setTabOrder(self.plainTextEdit_errormsg, self.radioButton_0)
        Dialog.setTabOrder(self.radioButton_0, self.radioButton_2)
        Dialog.setTabOrder(self.radioButton_2, self.radioButton_1)
        Dialog.setTabOrder(self.radioButton_1, self.pushButton_accept)
        Dialog.setTabOrder(self.pushButton_accept, self.pushButton_cancel)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "产品二维码"))
        self.pushButton_accept.setText(_translate("Dialog", "确认"))
        self.pushButton_cancel.setText(_translate("Dialog", "取消"))
        self.groupBox.setTitle(_translate("Dialog", "错误信息"))
        self.radioButton_0.setText(_translate("Dialog", "整箱出库"))
        self.radioButton_2.setText(_translate("Dialog", "合箱出库"))
        self.radioButton_1.setText(_translate("Dialog", "零头出库"))
from lib.mywidget.mylineedit import myQrcodeLineEdit
