# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stuffreturnlist.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(867, 587)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_refresh = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_refresh.sizePolicy().hasHeightForWidth())
        self.pushButton_refresh.setSizePolicy(sizePolicy)
        self.pushButton_refresh.setStyleSheet("")
        self.pushButton_refresh.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/images/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_refresh.setIcon(icon)
        self.pushButton_refresh.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_refresh.setObjectName("pushButton_refresh")
        self.horizontalLayout.addWidget(self.pushButton_refresh)
        self.printerButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.printerButton.sizePolicy().hasHeightForWidth())
        self.printerButton.setSizePolicy(sizePolicy)
        self.printerButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/logo/images/printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.printerButton.setIcon(icon1)
        self.printerButton.setIconSize(QtCore.QSize(30, 30))
        self.printerButton.setObjectName("printerButton")
        self.horizontalLayout.addWidget(self.printerButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_0 = QtWidgets.QWidget()
        self.tab_0.setObjectName("tab_0")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stuffdrawpaperlist = QtWidgets.QTreeWidget(self.tab_0)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(12)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.stuffdrawpaperlist.sizePolicy().hasHeightForWidth())
        self.stuffdrawpaperlist.setSizePolicy(sizePolicy)
        self.stuffdrawpaperlist.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.stuffdrawpaperlist.setObjectName("stuffdrawpaperlist")
        self.gridLayout_2.addWidget(self.stuffdrawpaperlist, 0, 0, 1, 1)
        self.countlabel = QtWidgets.QLabel(self.tab_0)
        self.countlabel.setObjectName("countlabel")
        self.gridLayout_2.addWidget(self.countlabel, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_0, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.tabWidget.addTab(self.tab_1, "")
        self.gridLayout.addWidget(self.tabWidget, 2, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_refresh.setToolTip(_translate("Form", "<html><head/><body><p>刷新</p></body></html>"))
        self.printerButton.setToolTip(_translate("Form", "<html><head/><body><p>打印</p></body></html>"))
        self.stuffdrawpaperlist.headerItem().setText(0, _translate("Form", "id"))
        self.stuffdrawpaperlist.headerItem().setText(1, _translate("Form", "类别"))
        self.stuffdrawpaperlist.headerItem().setText(2, _translate("Form", "退料人"))
        self.stuffdrawpaperlist.headerItem().setText(3, _translate("Form", "申请时间"))
        self.stuffdrawpaperlist.headerItem().setText(4, _translate("Form", "收料人"))
        self.stuffdrawpaperlist.headerItem().setText(5, _translate("Form", "收料时间"))
        self.stuffdrawpaperlist.headerItem().setText(6, _translate("Form", "产品"))
        self.stuffdrawpaperlist.headerItem().setText(7, _translate("Form", "产品含量规格"))
        self.stuffdrawpaperlist.headerItem().setText(8, _translate("Form", "产品包装规格"))
        self.stuffdrawpaperlist.headerItem().setText(9, _translate("Form", "产品批号"))
        self.countlabel.setText(_translate("Form", "共0条记录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_0), _translate("Form", "已提交"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Form", "已完成"))
import stuffimages_rc
