# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainmenu.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from clerks.views.deptmentandclerksUI import Ui_clerks

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(792, 599)
        clerks = Ui_clerks()
        clerks.setupUi(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/window/images/mainwindowlogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 390, 221, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.usrnamelabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.usrnamelabel.setAlignment(QtCore.Qt.AlignCenter)
        self.usrnamelabel.setObjectName("usrnamelabel")
        self.gridLayout.addWidget(self.usrnamelabel, 0, 0, 1, 1)
        self.deptlabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.deptlabel.setAlignment(QtCore.Qt.AlignCenter)
        self.deptlabel.setObjectName("deptlabel")
        self.gridLayout.addWidget(self.deptlabel, 1, 0, 1, 1)
        self.usrname = QtWidgets.QLabel(self.gridLayoutWidget)
        self.usrname.setText("")
        self.usrname.setAlignment(QtCore.Qt.AlignCenter)
        self.usrname.setObjectName("usrname")
        self.gridLayout.addWidget(self.usrname, 0, 1, 1, 1)
        self.deptname = QtWidgets.QLabel(self.gridLayoutWidget)
        self.deptname.setAlignment(QtCore.Qt.AlignCenter)
        self.deptname.setObjectName("deptname")
        self.gridLayout.addWidget(self.deptname, 1, 1, 1, 1)
        self.datatime = QtWidgets.QLabel(self.gridLayoutWidget)
        self.datatime.setAlignment(QtCore.Qt.AlignCenter)
        self.datatime.setObjectName("datatime")
        self.gridLayout.addWidget(self.datatime, 2, 0, 1, 2)
        self.menulist = QtWidgets.QTreeWidget(self.centralwidget)
        self.menulist.setGeometry(QtCore.QRect(50, 50, 220, 371))
        self.menulist.setStyleSheet("")
        self.menulist.setIndentation(0)
        self.menulist.setObjectName("menulist")
        item_0 = QtWidgets.QTreeWidgetItem(self.menulist)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.menulist)
        item_0 = QtWidgets.QTreeWidgetItem(self.menulist)
        item_0 = QtWidgets.QTreeWidgetItem(self.menulist)
        self.menulist.header().setCascadingSectionResizes(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(50, 50, 792, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_H = QtWidgets.QMenu(self.menubar)
        self.menu_H.setObjectName("menu_H")
        self.menu_D = QtWidgets.QMenu(self.menu_H)
        self.menu_D.setObjectName("menu_D")
        self.menu_V = QtWidgets.QMenu(self.menu_H)
        self.menu_V.setObjectName("menu_V")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actiondawe = QtWidgets.QAction(MainWindow)
        self.actiondawe.setObjectName("actiondawe")
        self.action70_8_5 = QtWidgets.QAction(MainWindow)
        self.action70_8_5.setObjectName("action70_8_5")
        self.action_E = QtWidgets.QAction(MainWindow)
        self.action_E.setObjectName("action_E")
        self.action_P = QtWidgets.QAction(MainWindow)
        self.action_P.setObjectName("action_P")
        self.action_Z = QtWidgets.QAction(MainWindow)
        self.action_Z.setObjectName("action_Z")
        self.action_ABOUT = QtWidgets.QAction(MainWindow)
        self.action_ABOUT.setObjectName("action_ABOUT")
        self.action_B = QtWidgets.QAction(MainWindow)
        self.action_B.setObjectName("action_B")
        self.action_B_2 = QtWidgets.QAction(MainWindow)
        self.action_B_2.setObjectName("action_B_2")
        self.action_P_2 = QtWidgets.QAction(MainWindow)
        self.action_P_2.setObjectName("action_P_2")
        self.action_P_3 = QtWidgets.QAction(MainWindow)
        self.action_P_3.setObjectName("action_P_3")
        self.action_Q = QtWidgets.QAction(MainWindow)
        self.action_Q.setObjectName("action_Q")
        self.action_Q_2 = QtWidgets.QAction(MainWindow)
        self.action_Q_2.setObjectName("action_Q_2")
        self.action_P_4 = QtWidgets.QAction(MainWindow)
        self.action_P_4.setObjectName("action_P_4")
        self.action_P_5 = QtWidgets.QAction(MainWindow)
        self.action_P_5.setObjectName("action_P_5")
        self.action_W = QtWidgets.QAction(MainWindow)
        self.action_W.setObjectName("action_W")
        self.action_W_2 = QtWidgets.QAction(MainWindow)
        self.action_W_2.setObjectName("action_W_2")
        self.action_E_2 = QtWidgets.QAction(MainWindow)
        self.action_E_2.setObjectName("action_E_2")
        self.action_E_3 = QtWidgets.QAction(MainWindow)
        self.action_E_3.setObjectName("action_E_3")
        self.action_S = QtWidgets.QAction(MainWindow)
        self.action_S.setObjectName("action_S")
        self.action_S_2 = QtWidgets.QAction(MainWindow)
        self.action_S_2.setObjectName("action_S_2")
        self.action_I = QtWidgets.QAction(MainWindow)
        self.action_I.setObjectName("action_I")
        self.action_I_2 = QtWidgets.QAction(MainWindow)
        self.action_I_2.setObjectName("action_I_2")
        self.action_M = QtWidgets.QAction(MainWindow)
        self.action_M.setObjectName("action_M")
        self.action_M_2 = QtWidgets.QAction(MainWindow)
        self.action_M_2.setObjectName("action_M_2")
        self.action_O = QtWidgets.QAction(MainWindow)
        self.action_O.setObjectName("action_O")
        self.action_O_2 = QtWidgets.QAction(MainWindow)
        self.action_O_2.setObjectName("action_O_2")
        self.menu.addAction(self.actiondawe)
        self.menu.addAction(self.action70_8_5)
        self.menu.addAction(self.action_E)
        self.menu.addAction(self.action_P)
        self.menu.addAction(self.action_Z)
        self.menu_D.addAction(self.action_B)
        self.menu_D.addAction(self.action_P_2)
        self.menu_D.addAction(self.action_Q)
        self.menu_D.addAction(self.action_P_4)
        self.menu_D.addAction(self.action_W)
        self.menu_D.addAction(self.action_E_2)
        self.menu_D.addAction(self.action_S)
        self.menu_D.addAction(self.action_I)
        self.menu_D.addAction(self.action_M)
        self.menu_D.addAction(self.action_O)
        self.menu_V.addAction(self.action_B_2)
        self.menu_V.addAction(self.action_P_3)
        self.menu_V.addAction(self.action_Q_2)
        self.menu_V.addAction(self.action_P_5)
        self.menu_V.addAction(self.action_W_2)
        self.menu_V.addAction(self.action_E_3)
        self.menu_V.addAction(self.action_S_2)
        self.menu_V.addAction(self.action_I_2)
        self.menu_V.addAction(self.action_M_2)
        self.menu_V.addAction(self.action_O_2)
        self.menu_H.addAction(self.action_ABOUT)
        self.menu_H.addSeparator()
        self.menu_H.addAction(self.menu_D.menuAction())
        self.menu_H.addSeparator()
        self.menu_H.addAction(self.menu_V.menuAction())
        self.menu_H.addSeparator()
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_H.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "主界面"))
        self.usrnamelabel.setText(_translate("MainWindow", "姓名"))
        self.deptlabel.setText(_translate("MainWindow", "部门"))
        self.deptname.setText(_translate("MainWindow", "TextLabel"))
        self.datatime.setText(_translate("MainWindow", "TextLabel"))
        self.menulist.headerItem().setText(0, _translate("MainWindow", "模块名"))
        __sortingEnabled = self.menulist.isSortingEnabled()
        self.menulist.setSortingEnabled(False)
        self.menulist.topLevelItem(0).setText(0, _translate("MainWindow", "基础资料"))
        self.menulist.topLevelItem(0).child(0).setText(0, _translate("MainWindow", "部门员工管理"))
        self.menulist.topLevelItem(0).child(1).setText(0, _translate("MainWindow", "物料字典"))
        self.menulist.topLevelItem(0).child(2).setText(0, _translate("MainWindow", "产品字典"))
        self.menulist.topLevelItem(0).child(3).setText(0, _translate("MainWindow", "供应商管理"))
        self.menulist.topLevelItem(0).child(4).setText(0, _translate("MainWindow", "自定义文档"))
        self.menulist.topLevelItem(0).child(5).setText(0, _translate("MainWindow", "新建子项目"))
        self.menulist.topLevelItem(0).child(6).setText(0, _translate("MainWindow", "系统设置"))
        self.menulist.topLevelItem(1).setText(0, _translate("MainWindow", "采购管理"))
        self.menulist.topLevelItem(2).setText(0, _translate("MainWindow", "质量管理"))
        self.menulist.topLevelItem(3).setText(0, _translate("MainWindow", "生产管理"))
        self.menulist.setSortingEnabled(__sortingEnabled)
        self.menu.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑(&E)"))
        self.menu_3.setTitle(_translate("MainWindow", "查询统计(&Q)"))
        self.menu_H.setTitle(_translate("MainWindow", "帮组(&H)"))
        self.menu_D.setTitle(_translate("MainWindow", "文档教程(&D)"))
        self.menu_V.setTitle(_translate("MainWindow", "视频教程(&V)"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actiondawe.setText(_translate("MainWindow", "重新登录(&L)"))
        self.action70_8_5.setText(_translate("MainWindow", "改变科室(&D)"))
        self.action_E.setText(_translate("MainWindow", "收发邮件(&E)"))
        self.action_P.setText(_translate("MainWindow", "修改密码(&P)"))
        self.action_Z.setText(_translate("MainWindow", "退出(&Z)"))
        self.action_ABOUT.setText(_translate("MainWindow", "关于(&A)"))
        self.action_B.setText(_translate("MainWindow", "基础资料(&B)"))
        self.action_B_2.setText(_translate("MainWindow", "基础资料(&B)"))
        self.action_P_2.setText(_translate("MainWindow", "采购管理(&P)"))
        self.action_P_3.setText(_translate("MainWindow", "采购管理(&P)"))
        self.action_Q.setText(_translate("MainWindow", "质量管理(&Q)"))
        self.action_Q_2.setText(_translate("MainWindow", "质量管理(&Q)"))
        self.action_P_4.setText(_translate("MainWindow", "生产管理(&P)"))
        self.action_P_5.setText(_translate("MainWindow", "生产管理(&P)"))
        self.action_W.setText(_translate("MainWindow", "仓库管理(&W)"))
        self.action_W_2.setText(_translate("MainWindow", "仓库管理(&W)"))
        self.action_E_2.setText(_translate("MainWindow", "设备管理(&E)"))
        self.action_E_3.setText(_translate("MainWindow", "设备管理(&E)"))
        self.action_S.setText(_translate("MainWindow", "销售管理(&S)"))
        self.action_S_2.setText(_translate("MainWindow", "销售管理(&S)"))
        self.action_I.setText(_translate("MainWindow", "综合管理(&I)"))
        self.action_I_2.setText(_translate("MainWindow", "综合管理(&I)"))
        self.action_M.setText(_translate("MainWindow", "物资管理(&M)"))
        self.action_M_2.setText(_translate("MainWindow", "物资管理(&M)"))
        self.action_O.setText(_translate("MainWindow", "其他(&O)"))
        self.action_O_2.setText(_translate("MainWindow", "其他(&O)"))
import menu.menuimages_rc
