# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editproducingplan.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(960, 480)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.planamount_label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.planamount_label.sizePolicy().hasHeightForWidth())
        self.planamount_label.setSizePolicy(sizePolicy)
        self.planamount_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.planamount_label.setObjectName("planamount_label")
        self.gridLayout.addWidget(self.planamount_label, 6, 0, 1, 1)
        self.meterial_treewidget = QtWidgets.QTreeWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meterial_treewidget.sizePolicy().hasHeightForWidth())
        self.meterial_treewidget.setSizePolicy(sizePolicy)
        self.meterial_treewidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.meterial_treewidget.setObjectName("meterial_treewidget")
        self.gridLayout.addWidget(self.meterial_treewidget, 1, 5, 5, 1)
        self.packageuse_label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.packageuse_label.sizePolicy().hasHeightForWidth())
        self.packageuse_label.setSizePolicy(sizePolicy)
        self.packageuse_label.setObjectName("packageuse_label")
        self.gridLayout.addWidget(self.packageuse_label, 6, 5, 1, 1)
        self.batchno_label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batchno_label.sizePolicy().hasHeightForWidth())
        self.batchno_label.setSizePolicy(sizePolicy)
        self.batchno_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.batchno_label.setObjectName("batchno_label")
        self.gridLayout.addWidget(self.batchno_label, 7, 0, 1, 1)
        self.commonname_label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commonname_label.sizePolicy().hasHeightForWidth())
        self.commonname_label.setSizePolicy(sizePolicy)
        self.commonname_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.commonname_label.setObjectName("commonname_label")
        self.gridLayout.addWidget(self.commonname_label, 3, 0, 1, 1)
        self.batchno = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.batchno.sizePolicy().hasHeightForWidth())
        self.batchno.setSizePolicy(sizePolicy)
        self.batchno.setObjectName("batchno")
        self.gridLayout.addWidget(self.batchno, 7, 3, 1, 1)
        self.productworkshop = QtWidgets.QLabel(Dialog)
        self.productworkshop.setText("")
        self.productworkshop.setObjectName("productworkshop")
        self.gridLayout.addWidget(self.productworkshop, 11, 3, 1, 1)
        self.prodline_label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prodline_label.sizePolicy().hasHeightForWidth())
        self.prodline_label.setSizePolicy(sizePolicy)
        self.prodline_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prodline_label.setObjectName("prodline_label")
        self.gridLayout.addWidget(self.prodline_label, 10, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.planamount = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.planamount.sizePolicy().hasHeightForWidth())
        self.planamount.setSizePolicy(sizePolicy)
        self.planamount.setObjectName("planamount")
        self.horizontalLayout.addWidget(self.planamount)
        self.unit = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.unit.sizePolicy().hasHeightForWidth())
        self.unit.setSizePolicy(sizePolicy)
        self.unit.setText("")
        self.unit.setObjectName("unit")
        self.horizontalLayout.addWidget(self.unit)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 3, 1, 1)
        self.productdate_label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productdate_label.sizePolicy().hasHeightForWidth())
        self.productdate_label.setSizePolicy(sizePolicy)
        self.productdate_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.productdate_label.setObjectName("productdate_label")
        self.gridLayout.addWidget(self.productdate_label, 8, 0, 1, 1)
        self.remarks_label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remarks_label.sizePolicy().hasHeightForWidth())
        self.remarks_label.setSizePolicy(sizePolicy)
        self.remarks_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.remarks_label.setObjectName("remarks_label")
        self.gridLayout.addWidget(self.remarks_label, 9, 0, 1, 1)
        self.productworkshop_label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productworkshop_label.sizePolicy().hasHeightForWidth())
        self.productworkshop_label.setSizePolicy(sizePolicy)
        self.productworkshop_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.productworkshop_label.setObjectName("productworkshop_label")
        self.gridLayout.addWidget(self.productworkshop_label, 11, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 4, 1, 1)
        self.prodline = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prodline.sizePolicy().hasHeightForWidth())
        self.prodline.setSizePolicy(sizePolicy)
        self.prodline.setText("")
        self.prodline.setObjectName("prodline")
        self.gridLayout.addWidget(self.prodline, 10, 3, 1, 1)
        self.remarks = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.remarks.sizePolicy().hasHeightForWidth())
        self.remarks.setSizePolicy(sizePolicy)
        self.remarks.setObjectName("remarks")
        self.gridLayout.addWidget(self.remarks, 9, 3, 1, 1)
        self.cancel_button = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_button.sizePolicy().hasHeightForWidth())
        self.cancel_button.setSizePolicy(sizePolicy)
        self.cancel_button.setObjectName("cancel_button")
        self.gridLayout.addWidget(self.cancel_button, 12, 5, 1, 1)
        self.accept_button = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accept_button.sizePolicy().hasHeightForWidth())
        self.accept_button.setSizePolicy(sizePolicy)
        self.accept_button.setObjectName("accept_button")
        self.gridLayout.addWidget(self.accept_button, 12, 3, 1, 1)
        self.package_treeWidget = QtWidgets.QTreeWidget(Dialog)
        self.package_treeWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.package_treeWidget.setObjectName("package_treeWidget")
        self.gridLayout.addWidget(self.package_treeWidget, 7, 5, 5, 1)
        self.productkind = QtWidgets.QComboBox(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.productkind.sizePolicy().hasHeightForWidth())
        self.productkind.setSizePolicy(sizePolicy)
        self.productkind.setObjectName("productkind")
        self.productkind.addItem("")
        self.productkind.addItem("")
        self.productkind.addItem("")
        self.gridLayout.addWidget(self.productkind, 1, 3, 1, 1)
        self.prodname_label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prodname_label.sizePolicy().hasHeightForWidth())
        self.prodname_label.setSizePolicy(sizePolicy)
        self.prodname_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.prodname_label.setObjectName("prodname_label")
        self.gridLayout.addWidget(self.prodname_label, 2, 0, 1, 1)
        self.editproductplan_label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editproductplan_label.sizePolicy().hasHeightForWidth())
        self.editproductplan_label.setSizePolicy(sizePolicy)
        self.editproductplan_label.setObjectName("editproductplan_label")
        self.gridLayout.addWidget(self.editproductplan_label, 0, 0, 1, 1)
        self.package_2 = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.package_2.sizePolicy().hasHeightForWidth())
        self.package_2.setSizePolicy(sizePolicy)
        self.package_2.setText("")
        self.package_2.setObjectName("package_2")
        self.gridLayout.addWidget(self.package_2, 5, 3, 1, 1)
        self.prodname = ComboLine(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prodname.sizePolicy().hasHeightForWidth())
        self.prodname.setSizePolicy(sizePolicy)
        self.prodname.setObjectName("prodname")
        self.gridLayout.addWidget(self.prodname, 2, 3, 1, 1)
        self.commonname = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.commonname.sizePolicy().hasHeightForWidth())
        self.commonname.setSizePolicy(sizePolicy)
        self.commonname.setText("")
        self.commonname.setObjectName("commonname")
        self.gridLayout.addWidget(self.commonname, 3, 3, 1, 1)
        self.materialuse_label = QtWidgets.QLabel(Dialog)
        self.materialuse_label.setObjectName("materialuse_label")
        self.gridLayout.addWidget(self.materialuse_label, 0, 5, 1, 1)
        self.spec_label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spec_label.sizePolicy().hasHeightForWidth())
        self.spec_label.setSizePolicy(sizePolicy)
        self.spec_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spec_label.setObjectName("spec_label")
        self.gridLayout.addWidget(self.spec_label, 4, 0, 1, 1)
        self.productkind_label = QtWidgets.QLabel(Dialog)
        self.productkind_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.productkind_label.setObjectName("productkind_label")
        self.gridLayout.addWidget(self.productkind_label, 1, 0, 1, 1)
        self.spec = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spec.sizePolicy().hasHeightForWidth())
        self.spec.setSizePolicy(sizePolicy)
        self.spec.setText("")
        self.spec.setObjectName("spec")
        self.gridLayout.addWidget(self.spec, 4, 3, 1, 1)
        self.package_label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.package_label.sizePolicy().hasHeightForWidth())
        self.package_label.setSizePolicy(sizePolicy)
        self.package_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.package_label.setObjectName("package_label")
        self.gridLayout.addWidget(self.package_label, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.makedate = QtWidgets.QDateEdit(Dialog)
        self.makedate.setCalendarPopup(True)
        self.makedate.setObjectName("makedate")
        self.horizontalLayout_2.addWidget(self.makedate)
        self.gridLayout.addLayout(self.horizontalLayout_2, 8, 3, 1, 1)
        self.package_2.raise_()
        self.spec.raise_()
        self.commonname.raise_()
        self.batchno.raise_()
        self.materialuse_label.raise_()
        self.packageuse_label.raise_()
        self.package_treeWidget.raise_()
        self.meterial_treewidget.raise_()
        self.productworkshop.raise_()
        self.prodline.raise_()
        self.label_5.raise_()
        self.remarks.raise_()
        self.prodline_label.raise_()
        self.productkind_label.raise_()
        self.editproductplan_label.raise_()
        self.productkind.raise_()
        self.prodname_label.raise_()
        self.package_label.raise_()
        self.planamount_label.raise_()
        self.spec_label.raise_()
        self.batchno_label.raise_()
        self.commonname_label.raise_()
        self.productdate_label.raise_()
        self.remarks_label.raise_()
        self.productworkshop_label.raise_()
        self.prodname.raise_()
        self.cancel_button.raise_()
        self.accept_button.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.productkind, self.prodname)
        Dialog.setTabOrder(self.prodname, self.planamount)
        Dialog.setTabOrder(self.planamount, self.batchno)
        Dialog.setTabOrder(self.batchno, self.makedate)
        Dialog.setTabOrder(self.makedate, self.remarks)
        Dialog.setTabOrder(self.remarks, self.accept_button)
        Dialog.setTabOrder(self.accept_button, self.cancel_button)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "编辑生产指令"))
        self.planamount_label.setText(_translate("Dialog", "计划产量："))
        self.meterial_treewidget.headerItem().setText(0, _translate("Dialog", "id"))
        self.meterial_treewidget.headerItem().setText(1, _translate("Dialog", "物料名称"))
        self.meterial_treewidget.headerItem().setText(2, _translate("Dialog", "配方"))
        self.meterial_treewidget.headerItem().setText(3, _translate("Dialog", "总需求量(不含损耗)"))
        self.meterial_treewidget.headerItem().setText(4, _translate("Dialog", "总需求量(含损耗)"))
        self.meterial_treewidget.headerItem().setText(5, _translate("Dialog", "库存实际量"))
        self.meterial_treewidget.headerItem().setText(6, _translate("Dialog", "库存有效量(折干折纯)"))
        self.meterial_treewidget.headerItem().setText(7, _translate("Dialog", "库存剩余量(库存有效量-已下指令但未领取的数量)"))
        self.meterial_treewidget.headerItem().setText(8, _translate("Dialog", "在途数量(已到货但未检验合格)"))
        self.packageuse_label.setText(_translate("Dialog", "包材使用量"))
        self.batchno_label.setText(_translate("Dialog", "批号："))
        self.commonname_label.setText(_translate("Dialog", "通用名："))
        self.prodline_label.setText(_translate("Dialog", "生产线："))
        self.productdate_label.setText(_translate("Dialog", "生产日期："))
        self.remarks_label.setText(_translate("Dialog", "备注："))
        self.productworkshop_label.setText(_translate("Dialog", "生产车间："))
        self.cancel_button.setText(_translate("Dialog", "取消"))
        self.accept_button.setText(_translate("Dialog", "确认"))
        self.package_treeWidget.headerItem().setText(0, _translate("Dialog", "id"))
        self.package_treeWidget.headerItem().setText(1, _translate("Dialog", "包材名称"))
        self.package_treeWidget.headerItem().setText(2, _translate("Dialog", "配方"))
        self.package_treeWidget.headerItem().setText(3, _translate("Dialog", "总需求量(不含损耗)"))
        self.package_treeWidget.headerItem().setText(4, _translate("Dialog", "总需求量(含损耗)"))
        self.package_treeWidget.headerItem().setText(5, _translate("Dialog", "库存实际量"))
        self.package_treeWidget.headerItem().setText(6, _translate("Dialog", "库存剩余量(库存有效量-已下指令但未领取的数量)"))
        self.package_treeWidget.headerItem().setText(7, _translate("Dialog", "在途数量(已到货但未检验合格)"))
        self.productkind.setItemText(0, _translate("Dialog", "成品"))
        self.productkind.setItemText(1, _translate("Dialog", "前处理"))
        self.productkind.setItemText(2, _translate("Dialog", "退货"))
        self.prodname_label.setText(_translate("Dialog", "产品商品名："))
        self.editproductplan_label.setText(_translate("Dialog", "编辑生产指令"))
        self.materialuse_label.setText(_translate("Dialog", "原料使用量"))
        self.spec_label.setText(_translate("Dialog", "含量规格："))
        self.productkind_label.setText(_translate("Dialog", "生产类型："))
        self.package_label.setText(_translate("Dialog", "包装规格；"))
from lib.mywidget.comboline import ComboLine
