# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'producingplan.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.produceButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.produceButton.sizePolicy().hasHeightForWidth())
        self.produceButton.setSizePolicy(sizePolicy)
        self.produceButton.setObjectName("produceButton")
        self.gridLayout.addWidget(self.produceButton, 1, 2, 1, 1)
        self.editButton = QtWidgets.QPushButton(Form)
        self.editButton.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editButton.sizePolicy().hasHeightForWidth())
        self.editButton.setSizePolicy(sizePolicy)
        self.editButton.setObjectName("editButton")
        self.gridLayout.addWidget(self.editButton, 1, 0, 1, 1)
        self.releaseButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.releaseButton.sizePolicy().hasHeightForWidth())
        self.releaseButton.setSizePolicy(sizePolicy)
        self.releaseButton.setObjectName("releaseButton")
        self.gridLayout.addWidget(self.releaseButton, 1, 1, 1, 1)
        self.productionrecords = QtWidgets.QTreeWidget(Form)
        self.productionrecords.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.productionrecords.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.productionrecords.setIndentation(0)
        self.productionrecords.setObjectName("productionrecords")
        self.gridLayout.addWidget(self.productionrecords, 2, 0, 1, 6)
        self.examineButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.examineButton.sizePolicy().hasHeightForWidth())
        self.examineButton.setSizePolicy(sizePolicy)
        self.examineButton.setObjectName("examineButton")
        self.gridLayout.addWidget(self.examineButton, 1, 3, 1, 1)
        self.finishedpushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.finishedpushButton.sizePolicy().hasHeightForWidth())
        self.finishedpushButton.setSizePolicy(sizePolicy)
        self.finishedpushButton.setObjectName("finishedpushButton")
        self.gridLayout.addWidget(self.finishedpushButton, 1, 4, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.refreshButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshButton.sizePolicy().hasHeightForWidth())
        self.refreshButton.setSizePolicy(sizePolicy)
        self.refreshButton.setStyleSheet("")
        self.refreshButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.refreshButton.setIcon(icon)
        self.refreshButton.setIconSize(QtCore.QSize(30, 30))
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout.addWidget(self.refreshButton)
        self.addButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton.setIcon(icon1)
        self.addButton.setIconSize(QtCore.QSize(30, 30))
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.deleteButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteButton.sizePolicy().hasHeightForWidth())
        self.deleteButton.setSizePolicy(sizePolicy)
        self.deleteButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.deleteButton.setIcon(icon2)
        self.deleteButton.setIconSize(QtCore.QSize(30, 30))
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton)
        self.queryButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.queryButton.sizePolicy().hasHeightForWidth())
        self.queryButton.setSizePolicy(sizePolicy)
        self.queryButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/query.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.queryButton.setIcon(icon3)
        self.queryButton.setIconSize(QtCore.QSize(30, 30))
        self.queryButton.setObjectName("queryButton")
        self.horizontalLayout.addWidget(self.queryButton)
        self.recordButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recordButton.sizePolicy().hasHeightForWidth())
        self.recordButton.setSizePolicy(sizePolicy)
        self.recordButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/record.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.recordButton.setIcon(icon4)
        self.recordButton.setIconSize(QtCore.QSize(30, 30))
        self.recordButton.setObjectName("recordButton")
        self.horizontalLayout.addWidget(self.recordButton)
        self.printerButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.printerButton.sizePolicy().hasHeightForWidth())
        self.printerButton.setSizePolicy(sizePolicy)
        self.printerButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.printerButton.setIcon(icon5)
        self.printerButton.setIconSize(QtCore.QSize(30, 30))
        self.printerButton.setObjectName("printerButton")
        self.horizontalLayout.addWidget(self.printerButton)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 4)
        self.countlabel = QtWidgets.QLabel(Form)
        self.countlabel.setObjectName("countlabel")
        self.gridLayout.addWidget(self.countlabel, 3, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.produceButton.setText(_translate("Form", "正在生产"))
        self.editButton.setText(_translate("Form", "未下达"))
        self.releaseButton.setText(_translate("Form", "已下达"))
        self.productionrecords.headerItem().setText(0, _translate("Form", "id"))
        self.productionrecords.headerItem().setText(1, _translate("Form", "产品编号"))
        self.productionrecords.headerItem().setText(2, _translate("Form", "产品商品名"))
        self.productionrecords.headerItem().setText(3, _translate("Form", "产品通用名"))
        self.productionrecords.headerItem().setText(4, _translate("Form", "批号"))
        self.productionrecords.headerItem().setText(5, _translate("Form", "含量规格"))
        self.productionrecords.headerItem().setText(6, _translate("Form", "包装规格"))
        self.productionrecords.headerItem().setText(7, _translate("Form", "剂型"))
        self.productionrecords.headerItem().setText(8, _translate("Form", "计划产量"))
        self.productionrecords.headerItem().setText(9, _translate("Form", "制订人"))
        self.productionrecords.headerItem().setText(10, _translate("Form", "下达时间"))
        self.productionrecords.headerItem().setText(11, _translate("Form", "生产日期"))
        self.productionrecords.headerItem().setText(12, _translate("Form", "审核人"))
        self.productionrecords.headerItem().setText(13, _translate("Form", "审核时间"))
        self.productionrecords.headerItem().setText(14, _translate("Form", "执行人"))
        self.productionrecords.headerItem().setText(15, _translate("Form", "执行时间"))
        self.productionrecords.headerItem().setText(16, _translate("Form", "生产线"))
        self.productionrecords.headerItem().setText(17, _translate("Form", "生产车间"))
        self.examineButton.setText(_translate("Form", "审核"))
        self.finishedpushButton.setText(_translate("Form", "生产结束"))
        self.refreshButton.setToolTip(_translate("Form", "<html><head/><body><p>刷新</p></body></html>"))
        self.addButton.setToolTip(_translate("Form", "<html><head/><body><p>增加记录</p></body></html>"))
        self.deleteButton.setToolTip(_translate("Form", "<html><head/><body><p>删除记录</p></body></html>"))
        self.queryButton.setToolTip(_translate("Form", "<html><head/><body><p>查找记录</p></body></html>"))
        self.recordButton.setToolTip(_translate("Form", "<html><head/><body><p>查看记录</p></body></html>"))
        self.printerButton.setToolTip(_translate("Form", "<html><head/><body><p>打印</p></body></html>"))
        self.countlabel.setText(_translate("Form", "共0条记录"))
import image_rc
