# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'saleorderlist.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(828, 574)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_0 = QtWidgets.QWidget()
        self.tab_0.setObjectName("tab_0")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeWidget_orderlist = QtWidgets.QTreeWidget(self.tab_0)
        self.treeWidget_orderlist.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeWidget_orderlist.setObjectName("treeWidget_orderlist")
        self.gridLayout_2.addWidget(self.treeWidget_orderlist, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_0)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.treeWidget_prodlist = QtWidgets.QTreeWidget(self.groupBox)
        self.treeWidget_prodlist.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeWidget_prodlist.setObjectName("treeWidget_prodlist")
        self.gridLayout_3.addWidget(self.treeWidget_prodlist, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab_0, "")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.treeWidget_orderlist.headerItem().setText(0, _translate("Form", "id"))
        self.treeWidget_orderlist.headerItem().setText(1, _translate("Form", "单号"))
        self.treeWidget_orderlist.headerItem().setText(2, _translate("Form", "客户"))
        self.treeWidget_orderlist.headerItem().setText(3, _translate("Form", "联系人"))
        self.treeWidget_orderlist.headerItem().setText(4, _translate("Form", "联系电话"))
        self.treeWidget_orderlist.headerItem().setText(5, _translate("Form", "销售日期"))
        self.treeWidget_orderlist.headerItem().setText(6, _translate("Form", "交货日期"))
        self.treeWidget_orderlist.headerItem().setText(7, _translate("Form", "交货地点"))
        self.treeWidget_orderlist.headerItem().setText(8, _translate("Form", "业务员"))
        self.treeWidget_orderlist.headerItem().setText(9, _translate("Form", "运输方式"))
        self.treeWidget_orderlist.headerItem().setText(10, _translate("Form", "付款方式"))
        self.treeWidget_orderlist.headerItem().setText(11, _translate("Form", "审核人"))
        self.treeWidget_orderlist.headerItem().setText(12, _translate("Form", "发货人"))
        self.treeWidget_orderlist.headerItem().setText(13, _translate("Form", "备注"))
        self.groupBox.setTitle(_translate("Form", "待售产品列表"))
        self.treeWidget_prodlist.headerItem().setText(0, _translate("Form", "id"))
        self.treeWidget_prodlist.headerItem().setText(1, _translate("Form", "产品"))
        self.treeWidget_prodlist.headerItem().setText(2, _translate("Form", "含量规格"))
        self.treeWidget_prodlist.headerItem().setText(3, _translate("Form", "包装规格"))
        self.treeWidget_prodlist.headerItem().setText(4, _translate("Form", "销售数量"))
        self.treeWidget_prodlist.headerItem().setText(5, _translate("Form", "单位"))
        self.treeWidget_prodlist.headerItem().setText(6, _translate("Form", "库存"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_0), _translate("Form", "编辑"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Form", "提交"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "发货"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "完成"))
