# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'applycheck.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(640, 480)
        self.gridLayout = QtWidgets.QGridLayout(dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_cancel = QtWidgets.QPushButton(dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cancel.sizePolicy().hasHeightForWidth())
        self.pushButton_cancel.setSizePolicy(sizePolicy)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 2, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.pushButton_apply = QtWidgets.QPushButton(dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_apply.sizePolicy().hasHeightForWidth())
        self.pushButton_apply.setSizePolicy(sizePolicy)
        self.pushButton_apply.setObjectName("pushButton_apply")
        self.gridLayout.addWidget(self.pushButton_apply, 0, 4, 1, 1)
        self.label_checkunit = QtWidgets.QLabel(dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_checkunit.sizePolicy().hasHeightForWidth())
        self.label_checkunit.setSizePolicy(sizePolicy)
        self.label_checkunit.setText("")
        self.label_checkunit.setObjectName("label_checkunit")
        self.gridLayout.addWidget(self.label_checkunit, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 1)
        self.lineEdit_checkamount = QtWidgets.QLineEdit(dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_checkamount.sizePolicy().hasHeightForWidth())
        self.lineEdit_checkamount.setSizePolicy(sizePolicy)
        self.lineEdit_checkamount.setObjectName("lineEdit_checkamount")
        self.gridLayout.addWidget(self.lineEdit_checkamount, 0, 1, 1, 2)
        self.comboBox_samplesource = QtWidgets.QComboBox(dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_samplesource.sizePolicy().hasHeightForWidth())
        self.comboBox_samplesource.setSizePolicy(sizePolicy)
        self.comboBox_samplesource.setEditable(True)
        self.comboBox_samplesource.setObjectName("comboBox_samplesource")
        self.gridLayout.addWidget(self.comboBox_samplesource, 2, 1, 1, 2)
        self.lineEdit_applyremark = QtWidgets.QLineEdit(dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_applyremark.sizePolicy().hasHeightForWidth())
        self.lineEdit_applyremark.setSizePolicy(sizePolicy)
        self.lineEdit_applyremark.setObjectName("lineEdit_applyremark")
        self.gridLayout.addWidget(self.lineEdit_applyremark, 4, 1, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeWidget_labitem = QtWidgets.QTreeWidget(self.groupBox)
        self.treeWidget_labitem.setIndentation(0)
        self.treeWidget_labitem.setObjectName("treeWidget_labitem")
        self.gridLayout_2.addWidget(self.treeWidget_labitem, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 5, 0, 1, 5)
        self.label_status = QtWidgets.QLabel(dialog)
        self.label_status.setText("")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setObjectName("label_status")
        self.gridLayout.addWidget(self.label_status, 4, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(dialog)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 3, 1, 1)

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "请验单"))
        self.pushButton_cancel.setText(_translate("dialog", "取消请验"))
        self.label_3.setText(_translate("dialog", "样品来源："))
        self.pushButton_apply.setText(_translate("dialog", "提交请验"))
        self.label.setText(_translate("dialog", "检品数量："))
        self.label_2.setText(_translate("dialog", "备注："))
        self.groupBox.setTitle(_translate("dialog", "待检项目"))
        self.treeWidget_labitem.headerItem().setText(0, _translate("dialog", "id"))
        self.treeWidget_labitem.headerItem().setText(1, _translate("dialog", "类别"))
        self.treeWidget_labitem.headerItem().setText(2, _translate("dialog", "项目"))
        self.label_4.setText(_translate("dialog", "状态："))
