# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'checkitem.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(558, 369)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.acceptbutton = QtWidgets.QPushButton(Dialog)
        self.acceptbutton.setObjectName("acceptbutton")
        self.gridLayout.addWidget(self.acceptbutton, 6, 2, 1, 1)
        self.cancelbutton = QtWidgets.QPushButton(Dialog)
        self.cancelbutton.setObjectName("cancelbutton")
        self.gridLayout.addWidget(self.cancelbutton, 6, 3, 1, 1)
        self.standardlabel = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.standardlabel.sizePolicy().hasHeightForWidth())
        self.standardlabel.setSizePolicy(sizePolicy)
        self.standardlabel.setObjectName("standardlabel")
        self.gridLayout.addWidget(self.standardlabel, 2, 0, 1, 1)
        self.seqid = QtWidgets.QLineEdit(Dialog)
        self.seqid.setObjectName("seqid")
        self.gridLayout.addWidget(self.seqid, 0, 1, 1, 1)
        self.typelabel = QtWidgets.QLabel(Dialog)
        self.typelabel.setObjectName("typelabel")
        self.gridLayout.addWidget(self.typelabel, 3, 0, 1, 1)
        self.itemlabel = QtWidgets.QLabel(Dialog)
        self.itemlabel.setObjectName("itemlabel")
        self.gridLayout.addWidget(self.itemlabel, 1, 3, 1, 1)
        self.itemname = QtWidgets.QLineEdit(Dialog)
        self.itemname.setObjectName("itemname")
        self.gridLayout.addWidget(self.itemname, 1, 4, 1, 1)
        self.kind = QtWidgets.QLineEdit(Dialog)
        self.kind.setObjectName("kind")
        self.gridLayout.addWidget(self.kind, 1, 1, 1, 1)
        self.restype = QtWidgets.QComboBox(Dialog)
        self.restype.setObjectName("restype")
        self.restype.addItem("")
        self.restype.addItem("")
        self.gridLayout.addWidget(self.restype, 3, 1, 1, 1)
        self.putintype = QtWidgets.QComboBox(Dialog)
        self.putintype.setObjectName("putintype")
        self.putintype.addItem("")
        self.putintype.addItem("")
        self.putintype.addItem("")
        self.putintype.addItem("")
        self.putintype.addItem("")
        self.putintype.addItem("")
        self.gridLayout.addWidget(self.putintype, 4, 1, 1, 1)
        self.referencevalue = QtWidgets.QTextEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.referencevalue.sizePolicy().hasHeightForWidth())
        self.referencevalue.setSizePolicy(sizePolicy)
        self.referencevalue.setObjectName("referencevalue")
        self.gridLayout.addWidget(self.referencevalue, 2, 1, 1, 4)
        self.inputlabel = QtWidgets.QLabel(Dialog)
        self.inputlabel.setObjectName("inputlabel")
        self.gridLayout.addWidget(self.inputlabel, 4, 0, 1, 1)
        self.nolabel = QtWidgets.QLabel(Dialog)
        self.nolabel.setObjectName("nolabel")
        self.gridLayout.addWidget(self.nolabel, 0, 0, 1, 1)
        self.classificationslabel = QtWidgets.QLabel(Dialog)
        self.classificationslabel.setObjectName("classificationslabel")
        self.gridLayout.addWidget(self.classificationslabel, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 5, 1, 1, 1)

        self.retranslateUi(Dialog)
        #QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "编辑检验项目"))
        self.acceptbutton.setText(_translate("Dialog", "确认"))
        self.cancelbutton.setText(_translate("Dialog", "取消"))
        self.standardlabel.setText(_translate("Dialog", "标准规定："))
        self.typelabel.setText(_translate("Dialog", "结果类型："))
        self.itemlabel.setText(_translate("Dialog", "项目名称："))
        self.restype.setItemText(0, _translate("Dialog", "文本"))
        self.restype.setItemText(1, _translate("Dialog", "数据"))
        self.putintype.setItemText(0, _translate("Dialog", "无"))
        self.putintype.setItemText(1, _translate("Dialog", "含量"))
        self.putintype.setItemText(2, _translate("Dialog", "水分"))
        self.putintype.setItemText(3, _translate("Dialog", "效价"))
        self.putintype.setItemText(4, _translate("Dialog", "相对密度"))
        self.putintype.setItemText(5, _translate("Dialog", "杂质"))
        self.inputlabel.setText(_translate("Dialog", "入库类别："))
        self.nolabel.setText(_translate("Dialog", "序号："))
        self.classificationslabel.setText(_translate("Dialog", "类别："))
