# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editcheckitem.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(694, 421)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.dateEdit_startdate = QtWidgets.QDateEdit(Dialog)
        self.dateEdit_startdate.setCalendarPopup(True)
        self.dateEdit_startdate.setObjectName("dateEdit_startdate")
        self.gridLayout.addWidget(self.dateEdit_startdate, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.dateEdit_enddate = QtWidgets.QDateEdit(Dialog)
        self.dateEdit_enddate.setCalendarPopup(True)
        self.dateEdit_enddate.setObjectName("dateEdit_enddate")
        self.gridLayout.addWidget(self.dateEdit_enddate, 1, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_accept = QtWidgets.QPushButton(Dialog)
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.horizontalLayout.addWidget(self.pushButton_accept)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_itemname = QtWidgets.QLabel(Dialog)
        self.label_itemname.setText("")
        self.label_itemname.setObjectName("label_itemname")
        self.gridLayout.addWidget(self.label_itemname, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.textEdit_labvalue = QtWidgets.QTextEdit(Dialog)
        self.textEdit_labvalue.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textEdit_labvalue.setObjectName("textEdit_labvalue")
        self.gridLayout.addWidget(self.textEdit_labvalue, 3, 1, 1, 3)
        self.textEdit_referencevalue = QtWidgets.QTextEdit(Dialog)
        self.textEdit_referencevalue.setEnabled(False)
        self.textEdit_referencevalue.setObjectName("textEdit_referencevalue")
        self.gridLayout.addWidget(self.textEdit_referencevalue, 2, 1, 1, 3)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.comboBox_result = QtWidgets.QComboBox(Dialog)
        self.comboBox_result.setObjectName("comboBox_result")
        self.comboBox_result.addItem("")
        self.comboBox_result.addItem("")
        self.gridLayout.addWidget(self.comboBox_result, 4, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "编辑检验结果"))
        self.label_7.setText(_translate("Dialog", "检验结束日期："))
        self.label_5.setText(_translate("Dialog", "检验开始日期："))
        self.pushButton_accept.setText(_translate("Dialog", "确认"))
        self.pushButton_cancel.setText(_translate("Dialog", "取消"))
        self.label.setText(_translate("Dialog", "项目名称："))
        self.label_2.setText(_translate("Dialog", "标准规定："))
        self.label_3.setText(_translate("Dialog", "检验结果："))
        self.label_8.setText(_translate("Dialog", "项目结论："))
        self.comboBox_result.setItemText(0, _translate("Dialog", "符合规定"))
        self.comboBox_result.setItemText(1, _translate("Dialog", "不符合规定"))
