# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'findcheckreportlist.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(980, 681)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.treeWidget_reportlist = QtWidgets.QTreeWidget(Dialog)
        self.treeWidget_reportlist.setObjectName("treeWidget_reportlist")
        self.gridLayout.addWidget(self.treeWidget_reportlist, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.treeWidget_reportlist.headerItem().setText(0, _translate("Dialog", "id"))
        self.treeWidget_reportlist.headerItem().setText(1, _translate("Dialog", "类型"))
        self.treeWidget_reportlist.headerItem().setText(2, _translate("Dialog", "报告编号"))
        self.treeWidget_reportlist.headerItem().setText(3, _translate("Dialog", "报告日期"))
        self.treeWidget_reportlist.headerItem().setText(4, _translate("Dialog", "结果"))
