# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'selectoricheckpaper.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 542)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_search = QtWidgets.QPushButton(Dialog)
        self.pushButton_search.setObjectName("pushButton_search")
        self.gridLayout.addWidget(self.pushButton_search, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_filename = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_filename.setObjectName("lineEdit_filename")
        self.gridLayout.addWidget(self.lineEdit_filename, 0, 1, 1, 1)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.gridLayout.addWidget(self.pushButton_cancel, 2, 2, 1, 1)
        self.pushButton_accept = QtWidgets.QPushButton(Dialog)
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.gridLayout.addWidget(self.pushButton_accept, 2, 1, 1, 1)
        self.treeWidget_filelist = QtWidgets.QTreeWidget(Dialog)
        self.treeWidget_filelist.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.treeWidget_filelist.setObjectName("treeWidget_filelist")
        self.gridLayout.addWidget(self.treeWidget_filelist, 1, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "新建原始检验记录"))
        self.pushButton_search.setText(_translate("Dialog", "查找"))
        self.label.setText(_translate("Dialog", "查找文档："))
        self.pushButton_cancel.setText(_translate("Dialog", "取消"))
        self.pushButton_accept.setText(_translate("Dialog", "确认"))
        self.treeWidget_filelist.headerItem().setText(0, _translate("Dialog", "id"))
        self.treeWidget_filelist.headerItem().setText(1, _translate("Dialog", "文件名"))
