# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(300, 200)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 0, 100, 40))
        self.label.setObjectName("label")
        self.Label = QtWidgets.QLabel(Dialog)
        self.Label.setGeometry(QtCore.QRect(50, 40, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Label.setFont(font)
        self.Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Label.setObjectName("Label")
        self.Label_2 = QtWidgets.QLabel(Dialog)
        self.Label_2.setGeometry(QtCore.QRect(50, 80, 40, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Label_2.setFont(font)
        self.Label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_2.setObjectName("Label_2")
        self.RadioButton_sign = QtWidgets.QRadioButton(Dialog)
        self.RadioButton_sign.setGeometry(QtCore.QRect(50, 130, 47, 16))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RadioButton_sign.sizePolicy().hasHeightForWidth())
        self.RadioButton_sign.setSizePolicy(sizePolicy)
        self.RadioButton_sign.setChecked(True)
        self.RadioButton_sign.setObjectName("RadioButton_sign")
        self.RadioButton_unsign = QtWidgets.QRadioButton(Dialog)
        self.RadioButton_unsign.setGeometry(QtCore.QRect(180, 130, 71, 16))
        self.RadioButton_unsign.setObjectName("RadioButton_unsign")
        self.acceptButton = QtWidgets.QPushButton(Dialog)
        self.acceptButton.setGeometry(QtCore.QRect(50, 160, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acceptButton.sizePolicy().hasHeightForWidth())
        self.acceptButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.acceptButton.setFont(font)
        self.acceptButton.setObjectName("acceptButton")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setEnabled(True)
        self.cancelButton.setGeometry(QtCore.QRect(180, 160, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setGeometry(QtCore.QRect(100, 80, 150, 20))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.tipslabel = QtWidgets.QLabel(Dialog)
        self.tipslabel.setEnabled(True)
        self.tipslabel.setGeometry(QtCore.QRect(100, 110, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tipslabel.setFont(font)
        self.tipslabel.setStyleSheet("color: rgb(255, 0, 0);")
        self.tipslabel.setObjectName("tipslabel")
        self.username = ComboLine(Dialog)
        self.username.setGeometry(QtCore.QRect(100, 40, 150, 20))
        self.username.setObjectName("username")
        self.tipslabel.raise_()
        self.password.raise_()
        self.acceptButton.raise_()
        self.cancelButton.raise_()
        self.RadioButton_sign.raise_()
        self.RadioButton_unsign.raise_()
        self.label.raise_()
        self.Label.raise_()
        self.Label_2.raise_()
        self.username.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.username, self.password)
        Dialog.setTabOrder(self.password, self.acceptButton)
        Dialog.setTabOrder(self.acceptButton, self.cancelButton)
        Dialog.setTabOrder(self.cancelButton, self.RadioButton_sign)
        Dialog.setTabOrder(self.RadioButton_sign, self.RadioButton_unsign)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "请选择用户签名："))
        self.Label.setText(_translate("Dialog", "姓名:"))
        self.Label_2.setText(_translate("Dialog", "密码:"))
        self.RadioButton_sign.setText(_translate("Dialog", "签名"))
        self.RadioButton_unsign.setText(_translate("Dialog", "清除签名"))
        self.acceptButton.setText(_translate("Dialog", "确认"))
        self.cancelButton.setText(_translate("Dialog", "取消"))
        self.tipslabel.setText(_translate("Dialog", "用户名/密码错误"))
from lib.mywidget.comboline import ComboLine
