# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'postdetail.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.treeWidget_equipment = QtWidgets.QTreeWidget(self.groupBox_3)
        self.treeWidget_equipment.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.treeWidget_equipment.setIndentation(0)
        self.treeWidget_equipment.setObjectName("treeWidget_equipment")
        self.gridLayout_7.addWidget(self.treeWidget_equipment, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 2)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_2)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.listWidget_postworker = QtWidgets.QListWidget(self.tab_1)
        self.listWidget_postworker.setObjectName("listWidget_postworker")
        self.gridLayout_4.addWidget(self.listWidget_postworker, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.treeWidget_document = QtWidgets.QTreeWidget(self.tab_2)
        self.treeWidget_document.setIndentation(0)
        self.treeWidget_document.setHeaderHidden(True)
        self.treeWidget_document.setObjectName("treeWidget_document")
        self.treeWidget_document.header().setVisible(False)
        self.gridLayout_5.addWidget(self.treeWidget_document, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.treeWidget_deviation = QtWidgets.QTreeWidget(self.tab_3)
        self.treeWidget_deviation.setIndentation(0)
        self.treeWidget_deviation.setObjectName("treeWidget_deviation")
        self.treeWidget_deviation.headerItem().setText(0, "1")
        self.treeWidget_deviation.header().setVisible(False)
        self.gridLayout_3.addWidget(self.treeWidget_deviation, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.dateTimeEdit_starttime = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit_starttime.setDate(QtCore.QDate(2020, 1, 1))
        self.dateTimeEdit_starttime.setCalendarPopup(True)
        self.dateTimeEdit_starttime.setCurrentSectionIndex(0)
        self.dateTimeEdit_starttime.setObjectName("dateTimeEdit_starttime")
        self.gridLayout_6.addWidget(self.dateTimeEdit_starttime, 4, 1, 1, 3)
        self.pushButton_endpost = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_endpost.setObjectName("pushButton_endpost")
        self.gridLayout_6.addWidget(self.pushButton_endpost, 6, 3, 1, 1)
        self.dateTimeEdit_endtime = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit_endtime.setCalendarPopup(True)
        self.dateTimeEdit_endtime.setObjectName("dateTimeEdit_endtime")
        self.gridLayout_6.addWidget(self.dateTimeEdit_endtime, 5, 1, 1, 3)
        self.lineEdit_temperature = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_temperature.sizePolicy().hasHeightForWidth())
        self.lineEdit_temperature.setSizePolicy(sizePolicy)
        self.lineEdit_temperature.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_temperature.setObjectName("lineEdit_temperature")
        self.gridLayout_6.addWidget(self.lineEdit_temperature, 2, 1, 1, 1)
        self.pushButton_startpost = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_startpost.sizePolicy().hasHeightForWidth())
        self.pushButton_startpost.setSizePolicy(sizePolicy)
        self.pushButton_startpost.setObjectName("pushButton_startpost")
        self.gridLayout_6.addWidget(self.pushButton_startpost, 6, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_postname = QtWidgets.QLabel(self.groupBox)
        self.label_postname.setText("")
        self.label_postname.setObjectName("label_postname")
        self.gridLayout_6.addWidget(self.label_postname, 0, 1, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_6.addWidget(self.label_7, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_6.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 5, 0, 1, 1)
        self.lineEdit_humidity = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_humidity.sizePolicy().hasHeightForWidth())
        self.lineEdit_humidity.setSizePolicy(sizePolicy)
        self.lineEdit_humidity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_humidity.setObjectName("lineEdit_humidity")
        self.gridLayout_6.addWidget(self.lineEdit_humidity, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 3, 2, 1, 1)
        self.comboBox_roomname = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_roomname.setEnabled(False)
        self.comboBox_roomname.setEditable(True)
        self.comboBox_roomname.setObjectName("comboBox_roomname")
        self.gridLayout_6.addWidget(self.comboBox_roomname, 1, 1, 1, 3)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.comboBox_roomname, self.lineEdit_temperature)
        Form.setTabOrder(self.lineEdit_temperature, self.lineEdit_humidity)
        Form.setTabOrder(self.lineEdit_humidity, self.dateTimeEdit_starttime)
        Form.setTabOrder(self.dateTimeEdit_starttime, self.dateTimeEdit_endtime)
        Form.setTabOrder(self.dateTimeEdit_endtime, self.pushButton_startpost)
        Form.setTabOrder(self.pushButton_startpost, self.pushButton_endpost)
        Form.setTabOrder(self.pushButton_endpost, self.treeWidget_equipment)
        Form.setTabOrder(self.treeWidget_equipment, self.tabWidget)
        Form.setTabOrder(self.tabWidget, self.treeWidget_document)
        Form.setTabOrder(self.treeWidget_document, self.listWidget_postworker)
        Form.setTabOrder(self.listWidget_postworker, self.treeWidget_deviation)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_3.setTitle(_translate("Form", "设备运行记录"))
        self.treeWidget_equipment.headerItem().setText(0, _translate("Form", "id"))
        self.treeWidget_equipment.headerItem().setText(1, _translate("Form", "设备"))
        self.treeWidget_equipment.headerItem().setText(2, _translate("Form", "填写人"))
        self.treeWidget_equipment.headerItem().setText(3, _translate("Form", "开始时间"))
        self.treeWidget_equipment.headerItem().setText(4, _translate("Form", "结束时间"))
        self.treeWidget_equipment.headerItem().setText(5, _translate("Form", "运行时间"))
        self.treeWidget_equipment.headerItem().setText(6, _translate("Form", "运行状态"))
        self.groupBox_2.setTitle(_translate("Form", "岗位信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Form", "岗位负责工人"))
        self.treeWidget_document.headerItem().setText(0, _translate("Form", "id"))
        self.treeWidget_document.headerItem().setText(1, _translate("Form", "文件编号"))
        self.treeWidget_document.headerItem().setText(2, _translate("Form", "文件名称"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "操作文档"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "偏差处理"))
        self.groupBox.setTitle(_translate("Form", "岗位操作"))
        self.pushButton_endpost.setText(_translate("Form", "结束岗位"))
        self.pushButton_startpost.setText(_translate("Form", "开始岗位"))
        self.label.setText(_translate("Form", "岗位名称："))
        self.label_5.setText(_translate("Form", "温度："))
        self.label_7.setText(_translate("Form", "开始生产时间："))
        self.label_6.setText(_translate("Form", "湿度："))
        self.label_2.setText(_translate("Form", "房间名称："))
        self.label_8.setText(_translate("Form", "结束生产时间："))
        self.label_3.setText(_translate("Form", "℃    "))
        self.label_4.setText(_translate("Form", "%"))
