# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editpurstuff.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(680, 215)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_amount = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_amount.sizePolicy().hasHeightForWidth())
        self.lineEdit_amount.setSizePolicy(sizePolicy)
        self.lineEdit_amount.setObjectName("lineEdit_amount")
        self.horizontalLayout.addWidget(self.lineEdit_amount)
        self.label_unit = QtWidgets.QLabel(Dialog)
        self.label_unit.setText("")
        self.label_unit.setObjectName("label_unit")
        self.horizontalLayout.addWidget(self.label_unit)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_package = QtWidgets.QLabel(Dialog)
        self.label_package.setText("")
        self.label_package.setObjectName("label_package")
        self.gridLayout.addWidget(self.label_package, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_accept = QtWidgets.QPushButton(Dialog)
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.horizontalLayout_2.addWidget(self.pushButton_accept)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_2.addWidget(self.pushButton_cancel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_2, 4, 0, 1, 2)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_spec = QtWidgets.QLabel(Dialog)
        self.label_spec.setText("")
        self.label_spec.setObjectName("label_spec")
        self.gridLayout.addWidget(self.label_spec, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_stuff = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_stuff.setEnabled(False)
        self.lineEdit_stuff.setObjectName("lineEdit_stuff")
        self.horizontalLayout_3.addWidget(self.lineEdit_stuff)
        self.toolButton_more = QtWidgets.QToolButton(Dialog)
        self.toolButton_more.setObjectName("toolButton_more")
        self.horizontalLayout_3.addWidget(self.toolButton_more)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "编辑采购物料"))
        self.label_4.setText(_translate("Dialog", "采购数量："))
        self.pushButton_accept.setText(_translate("Dialog", "确认"))
        self.pushButton_cancel.setText(_translate("Dialog", "取消"))
        self.label.setText(_translate("Dialog", "物料："))
        self.label_3.setText(_translate("Dialog", "包装规格："))
        self.label_2.setText(_translate("Dialog", "含量规格："))
        self.toolButton_more.setText(_translate("Dialog", "..."))
