# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editpurchasingplan.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 320)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_warrantor = SignButton(Dialog)
        self.pushButton_warrantor.setText("")
        self.pushButton_warrantor.setObjectName("pushButton_warrantor")
        self.gridLayout.addWidget(self.pushButton_warrantor, 6, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_accept = QtWidgets.QPushButton(Dialog)
        self.pushButton_accept.setObjectName("pushButton_accept")
        self.horizontalLayout.addWidget(self.pushButton_accept)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 7, 0, 1, 2)
        self.dateEdit_invaliddate = QtWidgets.QDateEdit(Dialog)
        self.dateEdit_invaliddate.setCalendarPopup(True)
        self.dateEdit_invaliddate.setObjectName("dateEdit_invaliddate")
        self.gridLayout.addWidget(self.dateEdit_invaliddate, 4, 1, 1, 1)
        self.lineEdit_remark = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_remark.setObjectName("lineEdit_remark")
        self.gridLayout.addWidget(self.lineEdit_remark, 5, 1, 1, 1)
        self.dateEdit_createdate = QtWidgets.QDateEdit(Dialog)
        self.dateEdit_createdate.setCalendarPopup(True)
        self.dateEdit_createdate.setObjectName("dateEdit_createdate")
        self.gridLayout.addWidget(self.dateEdit_createdate, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.pushButton_creator = SignButton(Dialog)
        self.pushButton_creator.setEnabled(True)
        self.pushButton_creator.setText("")
        self.pushButton_creator.setObjectName("pushButton_creator")
        self.gridLayout.addWidget(self.pushButton_creator, 2, 1, 1, 1)
        self.lineEdit_supplyer = ComboLine(Dialog)
        self.lineEdit_supplyer.setObjectName("lineEdit_supplyer")
        self.gridLayout.addWidget(self.lineEdit_supplyer, 1, 1, 1, 1)
        self.lineEdit_paperno = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_paperno.setObjectName("lineEdit_paperno")
        self.gridLayout.addWidget(self.lineEdit_paperno, 0, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.lineEdit_paperno, self.lineEdit_supplyer)
        Dialog.setTabOrder(self.lineEdit_supplyer, self.pushButton_creator)
        Dialog.setTabOrder(self.pushButton_creator, self.dateEdit_createdate)
        Dialog.setTabOrder(self.dateEdit_createdate, self.dateEdit_invaliddate)
        Dialog.setTabOrder(self.dateEdit_invaliddate, self.lineEdit_remark)
        Dialog.setTabOrder(self.lineEdit_remark, self.pushButton_warrantor)
        Dialog.setTabOrder(self.pushButton_warrantor, self.pushButton_accept)
        Dialog.setTabOrder(self.pushButton_accept, self.pushButton_cancel)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "编辑采购计划单"))
        self.label_3.setText(_translate("Dialog", "申请人："))
        self.label_4.setText(_translate("Dialog", "计划到货日期："))
        self.label_5.setText(_translate("Dialog", "备注："))
        self.label.setText(_translate("Dialog", "计划单号："))
        self.label_6.setText(_translate("Dialog", "批准人："))
        self.label_2.setText(_translate("Dialog", "供应商："))
        self.pushButton_accept.setText(_translate("Dialog", "确认"))
        self.pushButton_cancel.setText(_translate("Dialog", "取消"))
        self.label_7.setText(_translate("Dialog", "建立日期："))
from lib.mywidget.comboline import ComboLine
from lib.sign.signbutton import SignButton
