# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cleanconfirmity_copy.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(9, 9, 621, 341))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lineEdit_old_product = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_old_product.setObjectName("lineEdit_old_product")
        self.gridLayout_2.addWidget(self.lineEdit_old_product, 1, 1, 1, 1)
        self.lineEdit_new_product = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_new_product.setObjectName("lineEdit_new_product")
        self.gridLayout_2.addWidget(self.lineEdit_new_product, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 4, 0, 1, 1)
        self.lineEdit_postname = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_postname.setObjectName("lineEdit_postname")
        self.gridLayout_2.addWidget(self.lineEdit_postname, 0, 4, 1, 1)
        self.lineEdit_old_batchno = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_old_batchno.setObjectName("lineEdit_old_batchno")
        self.gridLayout_2.addWidget(self.lineEdit_old_batchno, 1, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 5, 3, 1, 1)
        self.lineEdit_new_batchno = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_new_batchno.setObjectName("lineEdit_new_batchno")
        self.gridLayout_2.addWidget(self.lineEdit_new_batchno, 2, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 3, 1, 1)
        self.lineEdit_sec_checkdate = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_sec_checkdate.setObjectName("lineEdit_sec_checkdate")
        self.gridLayout_2.addWidget(self.lineEdit_sec_checkdate, 9, 4, 1, 1)
        self.pushButton_sec_cleaner = SignButton(self.groupBox)
        self.pushButton_sec_cleaner.setText("")
        self.pushButton_sec_cleaner.setObjectName("pushButton_sec_cleaner")
        self.gridLayout_2.addWidget(self.pushButton_sec_cleaner, 8, 1, 1, 1)
        self.pushButton_sec_checker = SignButton(self.groupBox)
        self.pushButton_sec_checker.setText("")
        self.pushButton_sec_checker.setObjectName("pushButton_sec_checker")
        self.gridLayout_2.addWidget(self.pushButton_sec_checker, 9, 1, 1, 1)
        self.lineEdit_validdate = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_validdate.setObjectName("lineEdit_validdate")
        self.gridLayout_2.addWidget(self.lineEdit_validdate, 6, 1, 1, 1)
        self.label_sec_clean = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_sec_clean.sizePolicy().hasHeightForWidth())
        self.label_sec_clean.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_sec_clean.setFont(font)
        self.label_sec_clean.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_sec_clean.setObjectName("label_sec_clean")
        self.gridLayout_2.addWidget(self.label_sec_clean, 7, 0, 1, 1)
        self.label_sec_cleaner = QtWidgets.QLabel(self.groupBox)
        self.label_sec_cleaner.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_sec_cleaner.setObjectName("label_sec_cleaner")
        self.gridLayout_2.addWidget(self.label_sec_cleaner, 8, 0, 1, 1)
        self.lineEdit_cleandate = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_cleandate.setObjectName("lineEdit_cleandate")
        self.gridLayout_2.addWidget(self.lineEdit_cleandate, 4, 4, 1, 1)
        self.label_sec_cleandate = QtWidgets.QLabel(self.groupBox)
        self.label_sec_cleandate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_sec_cleandate.setObjectName("label_sec_cleandate")
        self.gridLayout_2.addWidget(self.label_sec_cleandate, 8, 3, 1, 1)
        self.lineEdit_checkdate = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_checkdate.setObjectName("lineEdit_checkdate")
        self.gridLayout_2.addWidget(self.lineEdit_checkdate, 5, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_sec_checkdate = QtWidgets.QLabel(self.groupBox)
        self.label_sec_checkdate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_sec_checkdate.setObjectName("label_sec_checkdate")
        self.gridLayout_2.addWidget(self.label_sec_checkdate, 9, 3, 1, 1)
        self.pushButton_cleaner = SignButton(self.groupBox)
        self.pushButton_cleaner.setText("")
        self.pushButton_cleaner.setObjectName("pushButton_cleaner")
        self.gridLayout_2.addWidget(self.pushButton_cleaner, 4, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 4, 3, 1, 1)
        self.label_sec_checker = QtWidgets.QLabel(self.groupBox)
        self.label_sec_checker.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_sec_checker.setObjectName("label_sec_checker")
        self.gridLayout_2.addWidget(self.label_sec_checker, 9, 0, 1, 1)
        self.lineEdit_sec_cleandate = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_sec_cleandate.setObjectName("lineEdit_sec_cleandate")
        self.gridLayout_2.addWidget(self.lineEdit_sec_cleandate, 8, 4, 1, 1)
        self.pushButton_checker = SignButton(self.groupBox)
        self.pushButton_checker.setText("")
        self.pushButton_checker.setObjectName("pushButton_checker")
        self.gridLayout_2.addWidget(self.pushButton_checker, 5, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 5)
        self.lineEdit_roomname = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_roomname.setObjectName("lineEdit_roomname")
        self.gridLayout_2.addWidget(self.lineEdit_roomname, 0, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "清场合格证副本"))
        self.label_2.setText(_translate("Form", "原生产品名："))
        self.label_10.setText(_translate("Form", "有效期至："))
        self.label_3.setText(_translate("Form", "调换产品名："))
        self.label.setText(_translate("Form", "房间："))
        self.label_8.setText(_translate("Form", "清场者："))
        self.label_14.setText(_translate("Form", "检查日期："))
        self.label_4.setText(_translate("Form", "工序："))
        self.label_5.setText(_translate("Form", "批号："))
        self.label_6.setText(_translate("Form", "批号："))
        self.label_sec_clean.setText(_translate("Form", "二次清场"))
        self.label_sec_cleaner.setText(_translate("Form", "二次清场者："))
        self.label_sec_cleandate.setText(_translate("Form", "二次清场日期："))
        self.label_9.setText(_translate("Form", "检查者："))
        self.label_sec_checkdate.setText(_translate("Form", "复查日期："))
        self.label_15.setText(_translate("Form", "清场日期："))
        self.label_sec_checker.setText(_translate("Form", "复查者："))
        self.label_7.setText(_translate("Form", "清场合格证（副本）"))
from lib.sign.signbutton import SignButton
